//=================================================
// GENERATED FILE, DON'T CHANGE MANUALLY
// GENERATED BY XmlModelGenerator
// To modify, adapt and run the XercesCodeGenerator
//=================================================
#include "generated/XmlBonuslist.h"

#include <assert.h>
#include <tchar.h>

#include "generated/XmlBonuscell.h"

namespace ww_1_2
{
XmlBonuslist::XmlBonuslist()
{
}

XmlBonuslist::~XmlBonuslist()
{
}



const std::vector<std::unique_ptr<XmlBonuscell>> & XmlBonuslist::GetBonuscellList() const
{
    return mBonuscellList;
}


void XmlBonuslist::Add(std::unique_ptr<XmlBonuscell> aBonuscell)
{
    mBonuscellList.push_back(std::move(aBonuscell));
}
}