//=================================================
// GENERATED FILE, DON'T CHANGE MANUALLY
// GENERATED BY XmlElementGenerator
// To modify, adapt and run the XercesCodeGenerator
//=================================================
#include "generated/XmlDag.h"

#include <assert.h>
#include <tchar.h>

#include "generated/XmlVoedingsmiddel.h"
#include "generated/XmlRecept.h"
#include "generated/XmlGerecht.h"
#include "generated/XmlHandmatigitem.h"
#include "generated/XmlBonuscell.h"

namespace ww_1_2
{
XmlDag::XmlDag()
{
}

XmlDag::~XmlDag()
{
}



const std::vector<std::unique_ptr<XmlVoedingsmiddel>> & XmlDag::GetVoedingsmiddelList() const
{
    return mVoedingsmiddelList;
}


const std::vector<std::unique_ptr<XmlRecept>> & XmlDag::GetReceptList() const
{
    return mReceptList;
}


const std::vector<std::unique_ptr<XmlGerecht>> & XmlDag::GetGerechtList() const
{
    return mGerechtList;
}


const std::vector<std::unique_ptr<XmlHandmatigitem>> & XmlDag::GetHandmatigitemList() const
{
    return mHandmatigitemList;
}


const std::vector<std::unique_ptr<XmlBonuscell>> & XmlDag::GetBonuscellList() const
{
    return mBonuscellList;
}


void XmlDag::Add(std::unique_ptr<XmlVoedingsmiddel> aVoedingsmiddel)
{
    mVoedingsmiddelList.push_back(std::move(aVoedingsmiddel));
}


void XmlDag::Add(std::unique_ptr<XmlRecept> aRecept)
{
    mReceptList.push_back(std::move(aRecept));
}


void XmlDag::Add(std::unique_ptr<XmlGerecht> aGerecht)
{
    mGerechtList.push_back(std::move(aGerecht));
}


void XmlDag::Add(std::unique_ptr<XmlHandmatigitem> aHandmatigitem)
{
    mHandmatigitemList.push_back(std::move(aHandmatigitem));
}


void XmlDag::Add(std::unique_ptr<XmlBonuscell> aBonuscell)
{
    mBonuscellList.push_back(std::move(aBonuscell));
}
std::string XmlDag::Getbonuspunten() const
{
    return mbonuspunten;
}

std::string XmlDag::Getdatum() const
{
    return mdatum;
}

std::string XmlDag::Getgewicht() const
{
    return mgewicht;
}

void XmlDag::Setbonuspunten(const std::string & abonuspunten)
{
    mbonuspunten = abonuspunten;
}

void XmlDag::Setdatum(const std::string & adatum)
{
    mdatum = adatum;
}

void XmlDag::Setgewicht(const std::string & agewicht)
{
    mgewicht = agewicht;
}

}