//=================================================
// GENERATED FILE, DON'T CHANGE MANUALLY
// GENERATED BY XmlElementWriterGenerator
// To modify, adapt and run the XercesCodeGenerator
//=================================================

//=================================
// Generated by XmlWriterGenerator 
//=================================

#include "generated/XmlFreelotWriter.h"

#include <xercesc/dom/dom.hpp>
#include <xercesc/framework/LocalFileFormatTarget.hpp>
#include <xercesc/parsers/XercesDOMParser.hpp>

#include <Utilities/strutils.h>

#include "generated/XmlFreelot.h"

namespace ww_1_2
{
XERCES_CPP_NAMESPACE::DOMNode * XmlFreelotWriter::Write(XERCES_CPP_NAMESPACE::DOMDocument & aDocument, const XmlFreelot & aFreelot)
{
    XERCES_CPP_NAMESPACE::DOMElement * element = aDocument.createElement(L"freelot");
    Fill(aDocument, aFreelot, *element);
    return element;
}

void XmlFreelotWriter::Fill(XERCES_CPP_NAMESPACE::DOMDocument & aDocument, const XmlFreelot & aFreelot, XERCES_CPP_NAMESPACE::DOMElement & anElement)
{
    (void)aDocument;
    (void)aFreelot;
    (void)anElement;
  anElement.setAttribute(L"punten", Str::ToWString(aFreelot.Getpunten()).c_str());
}


}
