//=================================================
// GENERATED FILE, DON'T CHANGE MANUALLY
// GENERATED BY XmlElementGenerator
// To modify, adapt and run the XercesCodeGenerator
//=================================================
#include "generated/XmlFreelot.h"

#include <assert.h>
#include <tchar.h>


namespace ww_1_2
{
XmlFreelot::XmlFreelot()
{
}

XmlFreelot::~XmlFreelot()
{
}

std::string XmlFreelot::Getpunten() const
{
    return mpunten;
}

void XmlFreelot::Setpunten(const std::string & apunten)
{
    mpunten = apunten;
}

}