//=================================================
// GENERATED FILE, DON'T CHANGE MANUALLY
// GENERATED BY XmlElementReaderGenerator
// To modify, adapt and run the XercesCodeGenerator
//=================================================
#include "generated/XmlFreelotReader.h"

#include <xercesc/dom/dom.hpp>
#include <xercesc/parsers/XercesDOMParser.hpp>

#include <Utilities/strutils.h>

#include "generated/XmlFreelot.h"


namespace ww_1_2
{
XmlFreelotReader::XmlFreelotReader()
{
}


std::unique_ptr<XmlFreelot> XmlFreelotReader::Generate(const XERCES_CPP_NAMESPACE::DOMNode & anElement)
{
    auto freelot = std::make_unique<XmlFreelot>();
    Fill(anElement, *freelot);
    return freelot;
}

XmlClass::Result XmlFreelotReader::Fill(const XERCES_CPP_NAMESPACE::DOMNode & anElement, XmlFreelot & aFreelot)
{
    const XERCES_CPP_NAMESPACE::DOMNodeList * list = anElement.getChildNodes();

    if (list == nullptr)
        return XmlClass::Result::Ok;

    for (XMLSize_t i = 0; i < list->getLength(); i++) {
        if (list->item(i) == nullptr)
            continue;

  }
    const XERCES_CPP_NAMESPACE::DOMNamedNodeMap * attributes = anElement.getAttributes();
    if (attributes != nullptr)
    {
    const XERCES_CPP_NAMESPACE::DOMNode* puntennode = attributes->getNamedItem(L"punten");
    if (puntennode != nullptr)
      aFreelot.Setpunten(Str::ToString(puntennode->getNodeValue()));
    }

    return XmlClass::Result::Ok;
}


}
