//=================================================
// GENERATED FILE, DON'T CHANGE MANUALLY
// GENERATED BY XmlElementReaderGenerator
// To modify, adapt and run the XercesCodeGenerator
//=================================================
#include "generated/XmlGerechtdefReader.h"

#include <xercesc/dom/dom.hpp>
#include <xercesc/parsers/XercesDOMParser.hpp>

#include <Utilities/strutils.h>

#include "generated/XmlGerechtdef.h"


namespace ww_1_2
{
XmlGerechtdefReader::XmlGerechtdefReader()
{
}


std::unique_ptr<XmlGerechtdef> XmlGerechtdefReader::Generate(const XERCES_CPP_NAMESPACE::DOMNode & anElement)
{
    auto gerechtdef = std::make_unique<XmlGerechtdef>();
    Fill(anElement, *gerechtdef);
    return gerechtdef;
}

XmlClass::Result XmlGerechtdefReader::Fill(const XERCES_CPP_NAMESPACE::DOMNode & anElement, XmlGerechtdef & aGerechtdef)
{
    const XERCES_CPP_NAMESPACE::DOMNodeList * list = anElement.getChildNodes();

    if (list == nullptr)
        return XmlClass::Result::Ok;

    for (XMLSize_t i = 0; i < list->getLength(); i++) {
        if (list->item(i) == nullptr)
            continue;

  }
    const XERCES_CPP_NAMESPACE::DOMNamedNodeMap * attributes = anElement.getAttributes();
    if (attributes != nullptr)
    {
    const XERCES_CPP_NAMESPACE::DOMNode* naamnode = attributes->getNamedItem(L"naam");
    if (naamnode != nullptr)
      aGerechtdef.Setnaam(Str::ToString(naamnode->getNodeValue()));
    const XERCES_CPP_NAMESPACE::DOMNode* puntennode = attributes->getNamedItem(L"punten");
    if (puntennode != nullptr)
      aGerechtdef.Setpunten(Str::ToString(puntennode->getNodeValue()));
    }

    return XmlClass::Result::Ok;
}


}
