//=================================================
// GENERATED FILE, DON'T CHANGE MANUALLY
// GENERATED BY XmlElementGenerator
// To modify, adapt and run the XercesCodeGenerator
//=================================================
#include "generated/XmlGerecht.h"

#include <assert.h>
#include <tchar.h>


namespace ww_1_2
{
XmlGerecht::XmlGerecht()
{
}

XmlGerecht::~XmlGerecht()
{
}

std::string XmlGerecht::Getnaam() const
{
    return mnaam;
}

std::string XmlGerecht::Getpunten() const
{
    return mpunten;
}

std::string XmlGerecht::Gethoeveelheid() const
{
    return mhoeveelheid;
}

void XmlGerecht::Setnaam(const std::string & anaam)
{
    mnaam = anaam;
}

void XmlGerecht::Setpunten(const std::string & apunten)
{
    mpunten = apunten;
}

void XmlGerecht::Sethoeveelheid(const std::string & ahoeveelheid)
{
    mhoeveelheid = ahoeveelheid;
}

}