//=================================================
// GENERATED FILE, DON'T CHANGE MANUALLY
// GENERATED BY XmlModelGenerator
// To modify, adapt and run the XercesCodeGenerator
//=================================================
#include "generated/XmlGerechtdefs.h"

#include <assert.h>
#include <tchar.h>

#include "generated/XmlGerechtdef.h"

namespace ww_1_2
{
XmlGerechtdefs::XmlGerechtdefs()
{
}

XmlGerechtdefs::~XmlGerechtdefs()
{
}



const std::vector<std::unique_ptr<XmlGerechtdef>> & XmlGerechtdefs::GetGerechtdefList() const
{
    return mGerechtdefList;
}


void XmlGerechtdefs::Add(std::unique_ptr<XmlGerechtdef> aGerechtdef)
{
    mGerechtdefList.push_back(std::move(aGerechtdef));
}
}