//=================================================
// GENERATED FILE, DON'T CHANGE MANUALLY
// GENERATED BY XmlElementWriterGenerator
// To modify, adapt and run the XercesCodeGenerator
//=================================================

//=================================
// Generated by XmlWriterGenerator 
//=================================

#include "generated/XmlGerechtWriter.h"

#include <xercesc/dom/dom.hpp>
#include <xercesc/framework/LocalFileFormatTarget.hpp>
#include <xercesc/parsers/XercesDOMParser.hpp>

#include <Utilities/strutils.h>

#include "generated/XmlGerecht.h"

namespace ww_1_2
{
XERCES_CPP_NAMESPACE::DOMNode * XmlGerechtWriter::Write(XERCES_CPP_NAMESPACE::DOMDocument & aDocument, const XmlGerecht & aGerecht)
{
    XERCES_CPP_NAMESPACE::DOMElement * element = aDocument.createElement(L"gerecht");
    Fill(aDocument, aGerecht, *element);
    return element;
}

void XmlGerechtWriter::Fill(XERCES_CPP_NAMESPACE::DOMDocument & aDocument, const XmlGerecht & aGerecht, XERCES_CPP_NAMESPACE::DOMElement & anElement)
{
    (void)aDocument;
    (void)aGerecht;
    (void)anElement;
  anElement.setAttribute(L"naam", Str::ToWString(aGerecht.Getnaam()).c_str());
  anElement.setAttribute(L"punten", Str::ToWString(aGerecht.Getpunten()).c_str());
  anElement.setAttribute(L"hoeveelheid", Str::ToWString(aGerecht.Gethoeveelheid()).c_str());
}


}
