//=================================================
// GENERATED FILE, DON'T CHANGE MANUALLY
// GENERATED BY XmlElementWriterGenerator
// To modify, adapt and run the XercesCodeGenerator
//=================================================

//=================================
// Generated by XmlWriterGenerator 
//=================================

#include "generated/XmlGerechtdefWriter.h"

#include <xercesc/dom/dom.hpp>
#include <xercesc/framework/LocalFileFormatTarget.hpp>
#include <xercesc/parsers/XercesDOMParser.hpp>

#include <Utilities/strutils.h>

#include "generated/XmlGerechtdef.h"

namespace ww_1_2
{
XERCES_CPP_NAMESPACE::DOMNode * XmlGerechtdefWriter::Write(XERCES_CPP_NAMESPACE::DOMDocument & aDocument, const XmlGerechtdef & aGerechtdef)
{
    XERCES_CPP_NAMESPACE::DOMElement * element = aDocument.createElement(L"gerechtdef");
    Fill(aDocument, aGerechtdef, *element);
    return element;
}

void XmlGerechtdefWriter::Fill(XERCES_CPP_NAMESPACE::DOMDocument & aDocument, const XmlGerechtdef & aGerechtdef, XERCES_CPP_NAMESPACE::DOMElement & anElement)
{
    (void)aDocument;
    (void)aGerechtdef;
    (void)anElement;
  anElement.setAttribute(L"naam", Str::ToWString(aGerechtdef.Getnaam()).c_str());
  anElement.setAttribute(L"punten", Str::ToWString(aGerechtdef.Getpunten()).c_str());
}


}
