//=================================================
// GENERATED FILE, DON'T CHANGE MANUALLY
// GENERATED BY XmlElementGenerator
// To modify, adapt and run the XercesCodeGenerator
//=================================================
#include "generated/XmlGerechtdef.h"

#include <assert.h>
#include <tchar.h>


namespace ww_1_2
{
XmlGerechtdef::XmlGerechtdef()
{
}

XmlGerechtdef::~XmlGerechtdef()
{
}

std::string XmlGerechtdef::Getnaam() const
{
    return mnaam;
}

std::string XmlGerechtdef::Getpunten() const
{
    return mpunten;
}

void XmlGerechtdef::Setnaam(const std::string & anaam)
{
    mnaam = anaam;
}

void XmlGerechtdef::Setpunten(const std::string & apunten)
{
    mpunten = apunten;
}

}