//=================================================
// GENERATED FILE, DON'T CHANGE MANUALLY
// GENERATED BY XmlElementWriterGenerator
// To modify, adapt and run the XercesCodeGenerator
//=================================================

//=================================
// Generated by XmlWriterGenerator 
//=================================

#include "generated/XmlHandmatigitemWriter.h"

#include <xercesc/dom/dom.hpp>
#include <xercesc/framework/LocalFileFormatTarget.hpp>
#include <xercesc/parsers/XercesDOMParser.hpp>

#include <Utilities/strutils.h>

#include "generated/XmlHandmatigitem.h"

namespace ww_1_2
{
XERCES_CPP_NAMESPACE::DOMNode * XmlHandmatigitemWriter::Write(XERCES_CPP_NAMESPACE::DOMDocument & aDocument, const XmlHandmatigitem & aHandmatigitem)
{
    XERCES_CPP_NAMESPACE::DOMElement * element = aDocument.createElement(L"handmatigitem");
    Fill(aDocument, aHandmatigitem, *element);
    return element;
}

void XmlHandmatigitemWriter::Fill(XERCES_CPP_NAMESPACE::DOMDocument & aDocument, const XmlHandmatigitem & aHandmatigitem, XERCES_CPP_NAMESPACE::DOMElement & anElement)
{
    (void)aDocument;
    (void)aHandmatigitem;
    (void)anElement;
  anElement.setAttribute(L"naam", Str::ToWString(aHandmatigitem.Getnaam()).c_str());
  anElement.setAttribute(L"punten", Str::ToWString(aHandmatigitem.Getpunten()).c_str());
  anElement.setAttribute(L"hoeveelheid", Str::ToWString(aHandmatigitem.Gethoeveelheid()).c_str());
}


}
