//=================================================
// GENERATED FILE, DON'T CHANGE MANUALLY
// GENERATED BY XmlElementGenerator
// To modify, adapt and run the XercesCodeGenerator
//=================================================
#include "generated/XmlHandmatigitem.h"

#include <assert.h>
#include <tchar.h>


namespace ww_1_2
{
XmlHandmatigitem::XmlHandmatigitem()
{
}

XmlHandmatigitem::~XmlHandmatigitem()
{
}

std::string XmlHandmatigitem::Getnaam() const
{
    return mnaam;
}

std::string XmlHandmatigitem::Getpunten() const
{
    return mpunten;
}

std::string XmlHandmatigitem::Gethoeveelheid() const
{
    return mhoeveelheid;
}

void XmlHandmatigitem::Setnaam(const std::string & anaam)
{
    mnaam = anaam;
}

void XmlHandmatigitem::Setpunten(const std::string & apunten)
{
    mpunten = apunten;
}

void XmlHandmatigitem::Sethoeveelheid(const std::string & ahoeveelheid)
{
    mhoeveelheid = ahoeveelheid;
}

}