//=================================================
// GENERATED FILE, DON'T CHANGE MANUALLY
// GENERATED BY XmlElementWriterGenerator
// To modify, adapt and run the XercesCodeGenerator
//=================================================

//=================================
// Generated by XmlWriterGenerator 
//=================================

#include "generated/XmlPortieWriter.h"

#include <xercesc/dom/dom.hpp>
#include <xercesc/framework/LocalFileFormatTarget.hpp>
#include <xercesc/parsers/XercesDOMParser.hpp>

#include <Utilities/strutils.h>

#include "generated/XmlPortie.h"

namespace ww_1_2
{
XERCES_CPP_NAMESPACE::DOMNode * XmlPortieWriter::Write(XERCES_CPP_NAMESPACE::DOMDocument & aDocument, const XmlPortie & aPortie)
{
    XERCES_CPP_NAMESPACE::DOMElement * element = aDocument.createElement(L"portie");
    Fill(aDocument, aPortie, *element);
    return element;
}

void XmlPortieWriter::Fill(XERCES_CPP_NAMESPACE::DOMDocument & aDocument, const XmlPortie & aPortie, XERCES_CPP_NAMESPACE::DOMElement & anElement)
{
    (void)aDocument;
    (void)aPortie;
    (void)anElement;
  anElement.setAttribute(L"naam", Str::ToWString(aPortie.Getnaam()).c_str());
  anElement.setAttribute(L"eenheden", Str::ToWString(aPortie.Geteenheden()).c_str());
}


}
