//=================================================
// GENERATED FILE, DON'T CHANGE MANUALLY
// GENERATED BY XmlElementWriterGenerator
// To modify, adapt and run the XercesCodeGenerator
//=================================================

//=================================
// Generated by XmlWriterGenerator 
//=================================

#include "generated/XmlPortieomschrijvingWriter.h"

#include <xercesc/dom/dom.hpp>
#include <xercesc/framework/LocalFileFormatTarget.hpp>
#include <xercesc/parsers/XercesDOMParser.hpp>

#include <Utilities/strutils.h>

#include "generated/XmlPortieomschrijving.h"

namespace ww_1_2
{
XERCES_CPP_NAMESPACE::DOMNode * XmlPortieomschrijvingWriter::Write(XERCES_CPP_NAMESPACE::DOMDocument & aDocument, const XmlPortieomschrijving & aPortieomschrijving)
{
    XERCES_CPP_NAMESPACE::DOMElement * element = aDocument.createElement(L"portieomschrijving");
    Fill(aDocument, aPortieomschrijving, *element);
    return element;
}

void XmlPortieomschrijvingWriter::Fill(XERCES_CPP_NAMESPACE::DOMDocument & aDocument, const XmlPortieomschrijving & aPortieomschrijving, XERCES_CPP_NAMESPACE::DOMElement & anElement)
{
    (void)aDocument;
    (void)aPortieomschrijving;
    (void)anElement;
  anElement.setAttribute(L"omschrijving", Str::ToWString(aPortieomschrijving.Getomschrijving()).c_str());
}


}
