//=================================================
// GENERATED FILE, DON'T CHANGE MANUALLY
// GENERATED BY XmlModelWriterGenerator
// To modify, adapt and run the XercesCodeGenerator
//=================================================

//=================================
// Generated by XmlWriterGenerator 
//=================================

#include "generated/XmlPersonaliaWriter.h"

#include <xercesc/dom/dom.hpp>
#include <xercesc/framework/LocalFileFormatTarget.hpp>
#include <xercesc/parsers/XercesDOMParser.hpp>

#include <Utilities/strutils.h>

#include "generated/XmlPersonalia.h"

namespace ww_1_2
{
XmlClass::Result XmlPersonaliaWriter::Write(const std::string & aFilename, const XmlPersonalia & aPersonalia)
{
    ParseErrorHandler eh;
    XERCES_CPP_NAMESPACE::XercesDOMParser parser;
    parser.setDoValidation(false);
    parser.setErrorHandler(&eh);

    XERCES_CPP_NAMESPACE::DOMImplementation* impl =
      XERCES_CPP_NAMESPACE::DOMImplementationRegistry::getDOMImplementation(L"Core");

    XERCES_CPP_NAMESPACE::DOMDocument* doc =
      impl->createDocument(0,               // root element namespace URI.
                           L"personalia",  // root element name
                           0);              // document type object (Xml).
    XERCES_CPP_NAMESPACE::DOMElement* rootelement = doc->getDocumentElement();
    Fill(*doc, aPersonalia, *rootelement);

    XERCES_CPP_NAMESPACE::DOMWriter* writer = ((XERCES_CPP_NAMESPACE::DOMImplementationLS*)impl)->createDOMWriter();
    XERCES_CPP_NAMESPACE::LocalFileFormatTarget formatter(aFilename.c_str());
    writer->writeNode(&formatter, *doc);
    writer->release();

    doc->release();

    return Result::Ok;
}


void XmlPersonaliaWriter::Fill(XERCES_CPP_NAMESPACE::DOMDocument & aDocument, const XmlPersonalia & aPersonalia, XERCES_CPP_NAMESPACE::DOMElement & anElement)
{
    (void)aDocument;
    (void)aPersonalia;
    (void)anElement;
  anElement.setAttribute(L"naam", Str::ToWString(aPersonalia.Getnaam()).c_str());
  anElement.setAttribute(L"gebruikersnaam", Str::ToWString(aPersonalia.Getgebruikersnaam()).c_str());
  anElement.setAttribute(L"punten", Str::ToWString(aPersonalia.Getpunten()).c_str());
  anElement.setAttribute(L"pppunten", Str::ToWString(aPersonalia.Getpppunten()).c_str());
  anElement.setAttribute(L"ppweekpunten", Str::ToWString(aPersonalia.Getppweekpunten()).c_str());
  anElement.setAttribute(L"kcpunten", Str::ToWString(aPersonalia.Getkcpunten()).c_str());
  anElement.setAttribute(L"kcweekpunten", Str::ToWString(aPersonalia.Getkcweekpunten()).c_str());
  anElement.setAttribute(L"chpunten", Str::ToWString(aPersonalia.Getchpunten()).c_str());
  anElement.setAttribute(L"chweekpunten", Str::ToWString(aPersonalia.Getchweekpunten()).c_str());
  anElement.setAttribute(L"geboren", Str::ToWString(aPersonalia.Getgeboren()).c_str());
    switch (aPersonalia.Getgeslacht())
    {
        case XmlPersonalia::geslacht::Mannelijk:
            anElement.setAttribute(L"geslacht", L"Mannelijk");
        break;
        case XmlPersonalia::geslacht::Vrouwelijk:
            anElement.setAttribute(L"geslacht", L"Vrouwelijk");
        break;
        default:
            throw 1;
    }
    switch (aPersonalia.Getwerk())
    {
        case XmlPersonalia::werk::Zittend:
            anElement.setAttribute(L"werk", L"Zittend");
        break;
        case XmlPersonalia::werk::Staand:
            anElement.setAttribute(L"werk", L"Staand");
        break;
        case XmlPersonalia::werk::Lopend:
            anElement.setAttribute(L"werk", L"Lopend");
        break;
        case XmlPersonalia::werk::Zwaar:
            anElement.setAttribute(L"werk", L"Zwaar");
        break;
        default:
            throw 1;
    }
  anElement.setAttribute(L"lengte", Str::ToWString(aPersonalia.Getlengte()).c_str());
  anElement.setAttribute(L"gewicht", Str::ToWString(aPersonalia.Getgewicht()).c_str());
  anElement.setAttribute(L"streefgewicht", Str::ToWString(aPersonalia.Getstreefgewicht()).c_str());
  anElement.setAttribute(L"startgewicht", Str::ToWString(aPersonalia.Getstartgewicht()).c_str());
  anElement.setAttribute(L"huidiggewicht", Str::ToWString(aPersonalia.Gethuidiggewicht()).c_str());
    switch (aPersonalia.Getstreven())
    {
        case XmlPersonalia::streven::Afvallen:
            anElement.setAttribute(L"streven", L"Afvallen");
        break;
        case XmlPersonalia::streven::OpGewichtBlijven:
            anElement.setAttribute(L"streven", L"OpGewichtBlijven");
        break;
        case XmlPersonalia::streven::Lopend:
            anElement.setAttribute(L"streven", L"Lopend");
        break;
        case XmlPersonalia::streven::Zwaar:
            anElement.setAttribute(L"streven", L"Zwaar");
        break;
        default:
            throw 1;
    }
    switch (aPersonalia.Getstrategie())
    {
        case XmlPersonalia::strategie::FlexiPoints:
            anElement.setAttribute(L"strategie", L"FlexiPoints");
        break;
        case XmlPersonalia::strategie::ProPoints:
            anElement.setAttribute(L"strategie", L"ProPoints");
        break;
        case XmlPersonalia::strategie::KCal:
            anElement.setAttribute(L"strategie", L"KCal");
        break;
        case XmlPersonalia::strategie::CarboHydrates:
            anElement.setAttribute(L"strategie", L"CarboHydrates");
        break;
        default:
            throw 1;
    }
}


}
