//=================================================
// GENERATED FILE, DON'T CHANGE MANUALLY
// GENERATED BY XmlElementGenerator
// To modify, adapt and run the XercesCodeGenerator
//=================================================
#include "generated/XmlPortieomschrijving.h"

#include <assert.h>
#include <tchar.h>


namespace ww_1_2
{
XmlPortieomschrijving::XmlPortieomschrijving()
{
}

XmlPortieomschrijving::~XmlPortieomschrijving()
{
}

std::string XmlPortieomschrijving::Getomschrijving() const
{
    return momschrijving;
}

void XmlPortieomschrijving::Setomschrijving(const std::string & aomschrijving)
{
    momschrijving = aomschrijving;
}

}