//=================================================
// GENERATED FILE, DON'T CHANGE MANUALLY
// GENERATED BY XmlElementGenerator
// To modify, adapt and run the XercesCodeGenerator
//=================================================
#include "generated/XmlPortie.h"

#include <assert.h>
#include <tchar.h>


namespace ww_1_2
{
XmlPortie::XmlPortie()
{
}

XmlPortie::~XmlPortie()
{
}

std::string XmlPortie::Getnaam() const
{
    return mnaam;
}

std::string XmlPortie::Geteenheden() const
{
    return meenheden;
}

void XmlPortie::Setnaam(const std::string & anaam)
{
    mnaam = anaam;
}

void XmlPortie::Seteenheden(const std::string & aeenheden)
{
    meenheden = aeenheden;
}

}