//=================================================
// GENERATED FILE, DON'T CHANGE MANUALLY
// GENERATED BY XmlElementReaderGenerator
// To modify, adapt and run the XercesCodeGenerator
//=================================================
#include "generated/XmlPuntenper100Reader.h"

#include <xercesc/dom/dom.hpp>
#include <xercesc/parsers/XercesDOMParser.hpp>

#include <Utilities/strutils.h>

#include "generated/XmlPuntenper100.h"


namespace ww_1_2
{
XmlPuntenper100Reader::XmlPuntenper100Reader()
{
}


std::unique_ptr<XmlPuntenper100> XmlPuntenper100Reader::Generate(const XERCES_CPP_NAMESPACE::DOMNode & anElement)
{
    auto puntenper100 = std::make_unique<XmlPuntenper100>();
    Fill(anElement, *puntenper100);
    return puntenper100;
}

XmlClass::Result XmlPuntenper100Reader::Fill(const XERCES_CPP_NAMESPACE::DOMNode & anElement, XmlPuntenper100 & aPuntenper100)
{
    const XERCES_CPP_NAMESPACE::DOMNodeList * list = anElement.getChildNodes();

    if (list == nullptr)
        return XmlClass::Result::Ok;

    for (XMLSize_t i = 0; i < list->getLength(); i++) {
        if (list->item(i) == nullptr)
            continue;

  }
    const XERCES_CPP_NAMESPACE::DOMNamedNodeMap * attributes = anElement.getAttributes();
    if (attributes != nullptr)
    {
    const XERCES_CPP_NAMESPACE::DOMNode* puntennode = attributes->getNamedItem(L"punten");
    if (puntennode != nullptr)
      aPuntenper100.Setpunten(Str::ToString(puntennode->getNodeValue()));
    }

    return XmlClass::Result::Ok;
}


}
