//=================================================
// GENERATED FILE, DON'T CHANGE MANUALLY
// GENERATED BY XmlElementGenerator
// To modify, adapt and run the XercesCodeGenerator
//=================================================
#include "generated/XmlPuntenper100.h"

#include <assert.h>
#include <tchar.h>


namespace ww_1_2
{
XmlPuntenper100::XmlPuntenper100()
{
}

XmlPuntenper100::~XmlPuntenper100()
{
}

std::string XmlPuntenper100::Getpunten() const
{
    return mpunten;
}

void XmlPuntenper100::Setpunten(const std::string & apunten)
{
    mpunten = apunten;
}

}