//=================================================
// GENERATED FILE, DON'T CHANGE MANUALLY
// GENERATED BY XmlModelGenerator
// To modify, adapt and run the XercesCodeGenerator
//=================================================
#include "generated/XmlPersonalia.h"

#include <assert.h>
#include <tchar.h>


namespace ww_1_2
{
XmlPersonalia::XmlPersonalia()
    : mgeslacht(geslacht::Mannelijk)
    , mwerk(werk::Zittend)
    , mstreven(streven::Afvallen)
    , mstrategie(strategie::ProPoints)

{
}

XmlPersonalia::~XmlPersonalia()
{
}

std::string XmlPersonalia::Getnaam() const
{
    return mnaam;
}

std::string XmlPersonalia::Getgebruikersnaam() const
{
    return mgebruikersnaam;
}

std::string XmlPersonalia::Getpunten() const
{
    return mpunten;
}

std::string XmlPersonalia::Getpppunten() const
{
    return mpppunten;
}

std::string XmlPersonalia::Getppweekpunten() const
{
    return mppweekpunten;
}

std::string XmlPersonalia::Getkcpunten() const
{
    return mkcpunten;
}

std::string XmlPersonalia::Getkcweekpunten() const
{
    return mkcweekpunten;
}

std::string XmlPersonalia::Getchpunten() const
{
    return mchpunten;
}

std::string XmlPersonalia::Getchweekpunten() const
{
    return mchweekpunten;
}

std::string XmlPersonalia::Getgeboren() const
{
    return mgeboren;
}

XmlPersonalia::geslacht XmlPersonalia::Getgeslacht() const
{
    return mgeslacht;
}

XmlPersonalia::werk XmlPersonalia::Getwerk() const
{
    return mwerk;
}

std::string XmlPersonalia::Getlengte() const
{
    return mlengte;
}

std::string XmlPersonalia::Getgewicht() const
{
    return mgewicht;
}

std::string XmlPersonalia::Getstreefgewicht() const
{
    return mstreefgewicht;
}

std::string XmlPersonalia::Getstartgewicht() const
{
    return mstartgewicht;
}

std::string XmlPersonalia::Gethuidiggewicht() const
{
    return mhuidiggewicht;
}

XmlPersonalia::streven XmlPersonalia::Getstreven() const
{
    return mstreven;
}

XmlPersonalia::strategie XmlPersonalia::Getstrategie() const
{
    return mstrategie;
}

void XmlPersonalia::Setnaam(const std::string & anaam)
{
    mnaam = anaam;
}

void XmlPersonalia::Setgebruikersnaam(const std::string & agebruikersnaam)
{
    mgebruikersnaam = agebruikersnaam;
}

void XmlPersonalia::Setpunten(const std::string & apunten)
{
    mpunten = apunten;
}

void XmlPersonalia::Setpppunten(const std::string & apppunten)
{
    mpppunten = apppunten;
}

void XmlPersonalia::Setppweekpunten(const std::string & appweekpunten)
{
    mppweekpunten = appweekpunten;
}

void XmlPersonalia::Setkcpunten(const std::string & akcpunten)
{
    mkcpunten = akcpunten;
}

void XmlPersonalia::Setkcweekpunten(const std::string & akcweekpunten)
{
    mkcweekpunten = akcweekpunten;
}

void XmlPersonalia::Setchpunten(const std::string & achpunten)
{
    mchpunten = achpunten;
}

void XmlPersonalia::Setchweekpunten(const std::string & achweekpunten)
{
    mchweekpunten = achweekpunten;
}

void XmlPersonalia::Setgeboren(const std::string & ageboren)
{
    mgeboren = ageboren;
}

void XmlPersonalia::Setgeslacht(geslacht ageslacht)
{
    mgeslacht = ageslacht;
}

void XmlPersonalia::Setwerk(werk awerk)
{
    mwerk = awerk;
}

void XmlPersonalia::Setlengte(const std::string & alengte)
{
    mlengte = alengte;
}

void XmlPersonalia::Setgewicht(const std::string & agewicht)
{
    mgewicht = agewicht;
}

void XmlPersonalia::Setstreefgewicht(const std::string & astreefgewicht)
{
    mstreefgewicht = astreefgewicht;
}

void XmlPersonalia::Setstartgewicht(const std::string & astartgewicht)
{
    mstartgewicht = astartgewicht;
}

void XmlPersonalia::Sethuidiggewicht(const std::string & ahuidiggewicht)
{
    mhuidiggewicht = ahuidiggewicht;
}

void XmlPersonalia::Setstreven(streven astreven)
{
    mstreven = astreven;
}

void XmlPersonalia::Setstrategie(strategie astrategie)
{
    mstrategie = astrategie;
}

}