//=================================================
// GENERATED FILE, DON'T CHANGE MANUALLY
// GENERATED BY XmlElementReaderGenerator
// To modify, adapt and run the XercesCodeGenerator
//=================================================
#include "generated/XmlPortieomschrijvingReader.h"

#include <xercesc/dom/dom.hpp>
#include <xercesc/parsers/XercesDOMParser.hpp>

#include <Utilities/strutils.h>

#include "generated/XmlPortieomschrijving.h"


namespace ww_1_2
{
XmlPortieomschrijvingReader::XmlPortieomschrijvingReader()
{
}


std::unique_ptr<XmlPortieomschrijving> XmlPortieomschrijvingReader::Generate(const XERCES_CPP_NAMESPACE::DOMNode & anElement)
{
    auto portieomschrijving = std::make_unique<XmlPortieomschrijving>();
    Fill(anElement, *portieomschrijving);
    return portieomschrijving;
}

XmlClass::Result XmlPortieomschrijvingReader::Fill(const XERCES_CPP_NAMESPACE::DOMNode & anElement, XmlPortieomschrijving & aPortieomschrijving)
{
    const XERCES_CPP_NAMESPACE::DOMNodeList * list = anElement.getChildNodes();

    if (list == nullptr)
        return XmlClass::Result::Ok;

    for (XMLSize_t i = 0; i < list->getLength(); i++) {
        if (list->item(i) == nullptr)
            continue;

  }
    const XERCES_CPP_NAMESPACE::DOMNamedNodeMap * attributes = anElement.getAttributes();
    if (attributes != nullptr)
    {
    const XERCES_CPP_NAMESPACE::DOMNode* omschrijvingnode = attributes->getNamedItem(L"omschrijving");
    if (omschrijvingnode != nullptr)
      aPortieomschrijving.Setomschrijving(Str::ToString(omschrijvingnode->getNodeValue()));
    }

    return XmlClass::Result::Ok;
}


}
