//=================================================
// GENERATED FILE, DON'T CHANGE MANUALLY
// GENERATED BY XmlElementWriterGenerator
// To modify, adapt and run the XercesCodeGenerator
//=================================================

//=================================
// Generated by XmlWriterGenerator 
//=================================

#include "generated/XmlPuntenper100Writer.h"

#include <xercesc/dom/dom.hpp>
#include <xercesc/framework/LocalFileFormatTarget.hpp>
#include <xercesc/parsers/XercesDOMParser.hpp>

#include <Utilities/strutils.h>

#include "generated/XmlPuntenper100.h"

namespace ww_1_2
{
XERCES_CPP_NAMESPACE::DOMNode * XmlPuntenper100Writer::Write(XERCES_CPP_NAMESPACE::DOMDocument & aDocument, const XmlPuntenper100 & aPuntenper100)
{
    XERCES_CPP_NAMESPACE::DOMElement * element = aDocument.createElement(L"puntenper100");
    Fill(aDocument, aPuntenper100, *element);
    return element;
}

void XmlPuntenper100Writer::Fill(XERCES_CPP_NAMESPACE::DOMDocument & aDocument, const XmlPuntenper100 & aPuntenper100, XERCES_CPP_NAMESPACE::DOMElement & anElement)
{
    (void)aDocument;
    (void)aPuntenper100;
    (void)anElement;
  anElement.setAttribute(L"punten", Str::ToWString(aPuntenper100.Getpunten()).c_str());
}


}
