//=================================================
// GENERATED FILE, DON'T CHANGE MANUALLY
// GENERATED BY XmlElementGenerator
// To modify, adapt and run the XercesCodeGenerator
//=================================================
#include "generated/XmlRecept.h"

#include <assert.h>
#include <tchar.h>


namespace ww_1_2
{
XmlRecept::XmlRecept()
{
}

XmlRecept::~XmlRecept()
{
}

std::string XmlRecept::Getnaam() const
{
    return mnaam;
}

std::string XmlRecept::Getpunten() const
{
    return mpunten;
}

std::string XmlRecept::Gethoeveelheid() const
{
    return mhoeveelheid;
}

void XmlRecept::Setnaam(const std::string & anaam)
{
    mnaam = anaam;
}

void XmlRecept::Setpunten(const std::string & apunten)
{
    mpunten = apunten;
}

void XmlRecept::Sethoeveelheid(const std::string & ahoeveelheid)
{
    mhoeveelheid = ahoeveelheid;
}

}