//=================================================
// GENERATED FILE, DON'T CHANGE MANUALLY
// GENERATED BY XmlElementWriterGenerator
// To modify, adapt and run the XercesCodeGenerator
//=================================================

//=================================
// Generated by XmlWriterGenerator 
//=================================

#include "generated/XmlReceptWriter.h"

#include <xercesc/dom/dom.hpp>
#include <xercesc/framework/LocalFileFormatTarget.hpp>
#include <xercesc/parsers/XercesDOMParser.hpp>

#include <Utilities/strutils.h>

#include "generated/XmlRecept.h"

namespace ww_1_2
{
XERCES_CPP_NAMESPACE::DOMNode * XmlReceptWriter::Write(XERCES_CPP_NAMESPACE::DOMDocument & aDocument, const XmlRecept & aRecept)
{
    XERCES_CPP_NAMESPACE::DOMElement * element = aDocument.createElement(L"recept");
    Fill(aDocument, aRecept, *element);
    return element;
}

void XmlReceptWriter::Fill(XERCES_CPP_NAMESPACE::DOMDocument & aDocument, const XmlRecept & aRecept, XERCES_CPP_NAMESPACE::DOMElement & anElement)
{
    (void)aDocument;
    (void)aRecept;
    (void)anElement;
  anElement.setAttribute(L"naam", Str::ToWString(aRecept.Getnaam()).c_str());
  anElement.setAttribute(L"punten", Str::ToWString(aRecept.Getpunten()).c_str());
  anElement.setAttribute(L"hoeveelheid", Str::ToWString(aRecept.Gethoeveelheid()).c_str());
}


}
