//=================================================
// GENERATED FILE, DON'T CHANGE MANUALLY
// GENERATED BY XmlModelGenerator
// To modify, adapt and run the XercesCodeGenerator
//=================================================
#include "generated/XmlReceptdefs.h"

#include <assert.h>
#include <tchar.h>

#include "generated/XmlReceptdef.h"

namespace ww_1_2
{
XmlReceptdefs::XmlReceptdefs()
{
}

XmlReceptdefs::~XmlReceptdefs()
{
}



const std::vector<std::unique_ptr<XmlReceptdef>> & XmlReceptdefs::GetReceptdefList() const
{
    return mReceptdefList;
}


void XmlReceptdefs::Add(std::unique_ptr<XmlReceptdef> aReceptdef)
{
    mReceptdefList.push_back(std::move(aReceptdef));
}
}