//=================================================
// GENERATED FILE, DON'T CHANGE MANUALLY
// GENERATED BY XmlElementWriterGenerator
// To modify, adapt and run the XercesCodeGenerator
//=================================================

//=================================
// Generated by XmlWriterGenerator 
//=================================

#include "generated/XmlReceptdefWriter.h"

#include <xercesc/dom/dom.hpp>
#include <xercesc/framework/LocalFileFormatTarget.hpp>
#include <xercesc/parsers/XercesDOMParser.hpp>

#include <Utilities/strutils.h>

#include "generated/XmlReceptdef.h"

#include "generated/XmlVoedingsmiddelWriter.h"
#include "generated/XmlVoedingsmiddel.h"
#include "generated/XmlReceptWriter.h"
#include "generated/XmlRecept.h"
#include "generated/XmlGerechtWriter.h"
#include "generated/XmlGerecht.h"
#include "generated/XmlHandmatigitemWriter.h"
#include "generated/XmlHandmatigitem.h"
namespace ww_1_2
{
XERCES_CPP_NAMESPACE::DOMNode * XmlReceptdefWriter::Write(XERCES_CPP_NAMESPACE::DOMDocument & aDocument, const XmlReceptdef & aReceptdef)
{
    XERCES_CPP_NAMESPACE::DOMElement * element = aDocument.createElement(L"receptdef");
    Fill(aDocument, aReceptdef, *element);
    return element;
}

void XmlReceptdefWriter::Fill(XERCES_CPP_NAMESPACE::DOMDocument & aDocument, const XmlReceptdef & aReceptdef, XERCES_CPP_NAMESPACE::DOMElement & anElement)
{

    XmlVoedingsmiddelWriter Voedingsmiddelwriter;
    for (size_t i = 0; i < aReceptdef.GetVoedingsmiddelList().size(); ++i)
    {
        XERCES_CPP_NAMESPACE::DOMNode * Voedingsmiddelnode = Voedingsmiddelwriter.Write(aDocument, *aReceptdef.GetVoedingsmiddelList()[i]);
        anElement.appendChild(Voedingsmiddelnode);
    }

    XmlReceptWriter Receptwriter;
    for (size_t i = 0; i < aReceptdef.GetReceptList().size(); ++i)
    {
        XERCES_CPP_NAMESPACE::DOMNode * Receptnode = Receptwriter.Write(aDocument, *aReceptdef.GetReceptList()[i]);
        anElement.appendChild(Receptnode);
    }

    XmlGerechtWriter Gerechtwriter;
    for (size_t i = 0; i < aReceptdef.GetGerechtList().size(); ++i)
    {
        XERCES_CPP_NAMESPACE::DOMNode * Gerechtnode = Gerechtwriter.Write(aDocument, *aReceptdef.GetGerechtList()[i]);
        anElement.appendChild(Gerechtnode);
    }

    XmlHandmatigitemWriter Handmatigitemwriter;
    for (size_t i = 0; i < aReceptdef.GetHandmatigitemList().size(); ++i)
    {
        XERCES_CPP_NAMESPACE::DOMNode * Handmatigitemnode = Handmatigitemwriter.Write(aDocument, *aReceptdef.GetHandmatigitemList()[i]);
        anElement.appendChild(Handmatigitemnode);
    }
  anElement.setAttribute(L"naam", Str::ToWString(aReceptdef.Getnaam()).c_str());
  anElement.setAttribute(L"porties", Str::ToWString(aReceptdef.Getporties()).c_str());
}


}
