//=================================================
// GENERATED FILE, DON'T CHANGE MANUALLY
// GENERATED BY XmlElementReaderGenerator
// To modify, adapt and run the XercesCodeGenerator
//=================================================
#include "generated/XmlStandardlotReader.h"

#include <xercesc/dom/dom.hpp>
#include <xercesc/parsers/XercesDOMParser.hpp>

#include <Utilities/strutils.h>

#include "generated/XmlStandardlot.h"
#include "generated/XmlPortieReader.h"
#include "generated/XmlPortie.h"
#include "generated/XmlVoedingswaardeReader.h"
#include "generated/XmlVoedingswaarde.h"
#include "generated/XmlPuntenper100Reader.h"
#include "generated/XmlPuntenper100.h"


namespace ww_1_2
{
XmlStandardlotReader::XmlStandardlotReader()
{
}


std::unique_ptr<XmlStandardlot> XmlStandardlotReader::Generate(const XERCES_CPP_NAMESPACE::DOMNode & anElement)
{
    auto standardlot = std::make_unique<XmlStandardlot>();
    Fill(anElement, *standardlot);
    return standardlot;
}

XmlClass::Result XmlStandardlotReader::Fill(const XERCES_CPP_NAMESPACE::DOMNode & anElement, XmlStandardlot & aStandardlot)
{
    const XERCES_CPP_NAMESPACE::DOMNodeList * list = anElement.getChildNodes();

    if (list == nullptr)
        return XmlClass::Result::Ok;

    for (XMLSize_t i = 0; i < list->getLength(); i++) {
        if (list->item(i) == nullptr)
            continue;

        short type = list->item(i)->getNodeType();
        XERCES_CPP_NAMESPACE::DOMNode * node = list->item(i);

        if (type == XERCES_CPP_NAMESPACE::DOMNode::ELEMENT_NODE) {
     if (wcscmp(node->getNodeName(), L"portie") == 0)
     {
         XmlPortieReader portieReader;
         auto portie = portieReader.Generate(*node);
         if (portie != nullptr)
             aStandardlot.Setportie(std::move(portie)); 
     }
     else if (wcscmp(node->getNodeName(), L"voedingswaarde") == 0)
     {
         XmlVoedingswaardeReader voedingswaardeReader;
         auto voedingswaarde = voedingswaardeReader.Generate(*node);
         if (voedingswaarde != nullptr)
             aStandardlot.Setvoedingswaarde(std::move(voedingswaarde)); 
     }
     else if (wcscmp(node->getNodeName(), L"puntenper100") == 0)
     {
         XmlPuntenper100Reader puntenper100Reader;
         auto puntenper100 = puntenper100Reader.Generate(*node);
         if (puntenper100 != nullptr)
             aStandardlot.Setpuntenper100(std::move(puntenper100)); 
     }
   }
  }
    const XERCES_CPP_NAMESPACE::DOMNamedNodeMap * attributes = anElement.getAttributes();
    if (attributes != nullptr)
    {
    const XERCES_CPP_NAMESPACE::DOMNode* sterrelotnode = attributes->getNamedItem(L"sterrelot");
    if (sterrelotnode != nullptr)
    {
      if (wcscmp(sterrelotnode->getNodeValue(), L"yes") == 0)
        aStandardlot.Setsterrelot(XmlStandardlot::sterrelot::yes);
      else if (wcscmp(sterrelotnode->getNodeValue(), L"no") == 0)
        aStandardlot.Setsterrelot(XmlStandardlot::sterrelot::no);
    }
    const XERCES_CPP_NAMESPACE::DOMNode* hoeveelheidnode = attributes->getNamedItem(L"hoeveelheid");
    if (hoeveelheidnode != nullptr)
      aStandardlot.Sethoeveelheid(Str::ToString(hoeveelheidnode->getNodeValue()));
    }

    return XmlClass::Result::Ok;
}


}
