//=================================================
// GENERATED FILE, DON'T CHANGE MANUALLY
// GENERATED BY XmlElementGenerator
// To modify, adapt and run the XercesCodeGenerator
//=================================================
#include "generated/XmlStandardlot.h"

#include <assert.h>
#include <tchar.h>

#include "generated/XmlPortie.h"
#include "generated/XmlVoedingswaarde.h"
#include "generated/XmlPuntenper100.h"

namespace ww_1_2
{
XmlStandardlot::XmlStandardlot()
    : mPortie(nullptr)
    , mVoedingswaarde(nullptr)
    , mPuntenper100(nullptr)    , msterrelot(sterrelot::yes)

{
}

XmlStandardlot::~XmlStandardlot()
{
}

XmlPortie & XmlStandardlot::GetPortie()
{
    return *mPortie;
}

const XmlPortie & XmlStandardlot::GetPortie() const
{
    return *mPortie;
}
const XmlVoedingswaarde * XmlStandardlot::GetVoedingswaarde() const
{
    return mVoedingswaarde.get();
}
const XmlPuntenper100 * XmlStandardlot::GetPuntenper100() const
{
    return mPuntenper100.get();
}


void XmlStandardlot::Setportie(std::unique_ptr<XmlPortie> aPortie)
{
    assert(mPortie == nullptr);
    mPortie = std::move(aPortie);
}


void XmlStandardlot::Setvoedingswaarde(std::unique_ptr<XmlVoedingswaarde> aVoedingswaarde)
{
    assert(mVoedingswaarde == nullptr);
    mVoedingswaarde = std::move(aVoedingswaarde);
}


void XmlStandardlot::Setpuntenper100(std::unique_ptr<XmlPuntenper100> aPuntenper100)
{
    assert(mPuntenper100 == nullptr);
    mPuntenper100 = std::move(aPuntenper100);
}
XmlStandardlot::sterrelot XmlStandardlot::Getsterrelot() const
{
    return msterrelot;
}

std::string XmlStandardlot::Gethoeveelheid() const
{
    return mhoeveelheid;
}

void XmlStandardlot::Setsterrelot(sterrelot asterrelot)
{
    msterrelot = asterrelot;
}

void XmlStandardlot::Sethoeveelheid(const std::string & ahoeveelheid)
{
    mhoeveelheid = ahoeveelheid;
}

}