//=================================================
// GENERATED FILE, DON'T CHANGE MANUALLY
// GENERATED BY XmlElementWriterGenerator
// To modify, adapt and run the XercesCodeGenerator
//=================================================

//=================================
// Generated by XmlWriterGenerator 
//=================================

#include "generated/XmlStandardlotWriter.h"

#include <xercesc/dom/dom.hpp>
#include <xercesc/framework/LocalFileFormatTarget.hpp>
#include <xercesc/parsers/XercesDOMParser.hpp>

#include <Utilities/strutils.h>

#include "generated/XmlStandardlot.h"

#include "generated/XmlPortieWriter.h"
#include "generated/XmlPortie.h"
#include "generated/XmlVoedingswaardeWriter.h"
#include "generated/XmlVoedingswaarde.h"
#include "generated/XmlPuntenper100Writer.h"
#include "generated/XmlPuntenper100.h"
namespace ww_1_2
{
XERCES_CPP_NAMESPACE::DOMNode * XmlStandardlotWriter::Write(XERCES_CPP_NAMESPACE::DOMDocument & aDocument, const XmlStandardlot & aStandardlot)
{
    XERCES_CPP_NAMESPACE::DOMElement * element = aDocument.createElement(L"standardlot");
    Fill(aDocument, aStandardlot, *element);
    return element;
}

void XmlStandardlotWriter::Fill(XERCES_CPP_NAMESPACE::DOMDocument & aDocument, const XmlStandardlot & aStandardlot, XERCES_CPP_NAMESPACE::DOMElement & anElement)
{

    XmlPortieWriter Portiewriter;
    anElement.appendChild(Portiewriter.Write(aDocument, aStandardlot.GetPortie()));

    XmlVoedingswaardeWriter Voedingswaardewriter;
    if (aStandardlot.GetVoedingswaarde() != NULL)
        anElement.appendChild(Voedingswaardewriter.Write(aDocument, *aStandardlot.GetVoedingswaarde()));

    XmlPuntenper100Writer Puntenper100writer;
    if (aStandardlot.GetPuntenper100() != NULL)
        anElement.appendChild(Puntenper100writer.Write(aDocument, *aStandardlot.GetPuntenper100()));
    switch (aStandardlot.Getsterrelot())
    {
        case XmlStandardlot::sterrelot::yes:
            anElement.setAttribute(L"sterrelot", L"yes");
        break;
        case XmlStandardlot::sterrelot::no:
            anElement.setAttribute(L"sterrelot", L"no");
        break;
        default:
            throw 1;
    }
  anElement.setAttribute(L"hoeveelheid", Str::ToWString(aStandardlot.Gethoeveelheid()).c_str());
}


}
