//=================================================
// GENERATED FILE, DON'T CHANGE MANUALLY
// GENERATED BY XmlModelGenerator
// To modify, adapt and run the XercesCodeGenerator
//=================================================
#include "generated/XmlUnits.h"

#include <assert.h>
#include <tchar.h>

#include "generated/XmlUnit.h"

namespace ww_1_2
{
XmlUnits::XmlUnits()
{
}

XmlUnits::~XmlUnits()
{
}



const std::vector<std::unique_ptr<XmlUnit>> & XmlUnits::GetUnitList() const
{
    return mUnitList;
}


void XmlUnits::Add(std::unique_ptr<XmlUnit> aUnit)
{
    mUnitList.push_back(std::move(aUnit));
}
}