//=================================================
// GENERATED FILE, DON'T CHANGE MANUALLY
// GENERATED BY XmlElementGenerator
// To modify, adapt and run the XercesCodeGenerator
//=================================================
#include "generated/XmlUnit.h"

#include <assert.h>
#include <tchar.h>


namespace ww_1_2
{
XmlUnit::XmlUnit()
{
}

XmlUnit::~XmlUnit()
{
}

std::string XmlUnit::Getnaam() const
{
    return mnaam;
}

void XmlUnit::Setnaam(const std::string & anaam)
{
    mnaam = anaam;
}

}