//=================================================
// GENERATED FILE, DON'T CHANGE MANUALLY
// GENERATED BY XmlElementReaderGenerator
// To modify, adapt and run the XercesCodeGenerator
//=================================================
#include "generated/XmlVoedingsmiddelbasisReader.h"

#include <xercesc/dom/dom.hpp>
#include <xercesc/parsers/XercesDOMParser.hpp>

#include <Utilities/strutils.h>

#include "generated/XmlVoedingsmiddelbasis.h"
#include "generated/XmlVoedingsmiddelheaderReader.h"
#include "generated/XmlVoedingsmiddelheader.h"


namespace ww_1_2
{
XmlVoedingsmiddelbasisReader::XmlVoedingsmiddelbasisReader()
{
}


std::unique_ptr<XmlVoedingsmiddelbasis> XmlVoedingsmiddelbasisReader::Generate(const XERCES_CPP_NAMESPACE::DOMNode & anElement)
{
    auto voedingsmiddelbasis = std::make_unique<XmlVoedingsmiddelbasis>();
    Fill(anElement, *voedingsmiddelbasis);
    return voedingsmiddelbasis;
}

XmlClass::Result XmlVoedingsmiddelbasisReader::Fill(const XERCES_CPP_NAMESPACE::DOMNode & anElement, XmlVoedingsmiddelbasis & aVoedingsmiddelbasis)
{
    const XERCES_CPP_NAMESPACE::DOMNodeList * list = anElement.getChildNodes();

    if (list == nullptr)
        return XmlClass::Result::Ok;

    for (XMLSize_t i = 0; i < list->getLength(); i++) {
        if (list->item(i) == nullptr)
            continue;

        short type = list->item(i)->getNodeType();
        XERCES_CPP_NAMESPACE::DOMNode * node = list->item(i);

        if (type == XERCES_CPP_NAMESPACE::DOMNode::ELEMENT_NODE) {
     if (wcscmp(node->getNodeName(), L"voedingsmiddelheader") == 0)
     {
         XmlVoedingsmiddelheaderReader voedingsmiddelheaderReader;
         auto voedingsmiddelheader = voedingsmiddelheaderReader.Generate(*node);
         if (voedingsmiddelheader != nullptr)
             aVoedingsmiddelbasis.Setvoedingsmiddelheader(std::move(voedingsmiddelheader)); 
     }
   }
  }
    const XERCES_CPP_NAMESPACE::DOMNamedNodeMap * attributes = anElement.getAttributes();
    if (attributes != nullptr)
    {
    const XERCES_CPP_NAMESPACE::DOMNode* sterreportienode = attributes->getNamedItem(L"sterreportie");
    if (sterreportienode != nullptr)
      aVoedingsmiddelbasis.Setsterreportie(Str::ToString(sterreportienode->getNodeValue()));
    const XERCES_CPP_NAMESPACE::DOMNode* vrijeportienode = attributes->getNamedItem(L"vrijeportie");
    if (vrijeportienode != nullptr)
    {
      if (wcscmp(vrijeportienode->getNodeValue(), L"yes") == 0)
        aVoedingsmiddelbasis.Setvrijeportie(XmlVoedingsmiddelbasis::vrijeportie::yes);
      else if (wcscmp(vrijeportienode->getNodeValue(), L"no") == 0)
        aVoedingsmiddelbasis.Setvrijeportie(XmlVoedingsmiddelbasis::vrijeportie::no);
    }
    const XERCES_CPP_NAMESPACE::DOMNode* vrijepuntennode = attributes->getNamedItem(L"vrijepunten");
    if (vrijepuntennode != nullptr)
      aVoedingsmiddelbasis.Setvrijepunten(Str::ToString(vrijepuntennode->getNodeValue()));
    const XERCES_CPP_NAMESPACE::DOMNode* vrijeppportienode = attributes->getNamedItem(L"vrijeppportie");
    if (vrijeppportienode != nullptr)
    {
      if (wcscmp(vrijeppportienode->getNodeValue(), L"yes") == 0)
        aVoedingsmiddelbasis.Setvrijeppportie(XmlVoedingsmiddelbasis::vrijeppportie::yes);
      else if (wcscmp(vrijeppportienode->getNodeValue(), L"no") == 0)
        aVoedingsmiddelbasis.Setvrijeppportie(XmlVoedingsmiddelbasis::vrijeppportie::no);
    }
    const XERCES_CPP_NAMESPACE::DOMNode* vrijepppuntennode = attributes->getNamedItem(L"vrijepppunten");
    if (vrijepppuntennode != nullptr)
      aVoedingsmiddelbasis.Setvrijepppunten(Str::ToString(vrijepppuntennode->getNodeValue()));
    }

    return XmlClass::Result::Ok;
}


}
