//=================================================
// GENERATED FILE, DON'T CHANGE MANUALLY
// GENERATED BY XmlElementWriterGenerator
// To modify, adapt and run the XercesCodeGenerator
//=================================================

//=================================
// Generated by XmlWriterGenerator 
//=================================

#include "generated/XmlVoedingsmiddelWriter.h"

#include <xercesc/dom/dom.hpp>
#include <xercesc/framework/LocalFileFormatTarget.hpp>
#include <xercesc/parsers/XercesDOMParser.hpp>

#include <Utilities/strutils.h>

#include "generated/XmlVoedingsmiddel.h"

#include "generated/XmlStandardlotWriter.h"
#include "generated/XmlStandardlot.h"
#include "generated/XmlFreelotWriter.h"
#include "generated/XmlFreelot.h"
namespace ww_1_2
{
XERCES_CPP_NAMESPACE::DOMNode * XmlVoedingsmiddelWriter::Write(XERCES_CPP_NAMESPACE::DOMDocument & aDocument, const XmlVoedingsmiddel & aVoedingsmiddel)
{
    XERCES_CPP_NAMESPACE::DOMElement * element = aDocument.createElement(L"voedingsmiddel");
    Fill(aDocument, aVoedingsmiddel, *element);
    return element;
}

void XmlVoedingsmiddelWriter::Fill(XERCES_CPP_NAMESPACE::DOMDocument & aDocument, const XmlVoedingsmiddel & aVoedingsmiddel, XERCES_CPP_NAMESPACE::DOMElement & anElement)
{

    XmlStandardlotWriter Standardlotwriter;
    if (aVoedingsmiddel.GetStandardlot() != NULL)
        anElement.appendChild(Standardlotwriter.Write(aDocument, *aVoedingsmiddel.GetStandardlot()));

    XmlFreelotWriter Freelotwriter;
    if (aVoedingsmiddel.GetFreelot() != NULL)
        anElement.appendChild(Freelotwriter.Write(aDocument, *aVoedingsmiddel.GetFreelot()));
  anElement.setAttribute(L"naam", Str::ToWString(aVoedingsmiddel.Getnaam()).c_str());
  anElement.setAttribute(L"categorie", Str::ToWString(aVoedingsmiddel.Getcategorie()).c_str());
  if (!aVoedingsmiddel.Getmerk().empty())
    anElement.setAttribute(L"merk", Str::ToWString(aVoedingsmiddel.Getmerk()).c_str());
  anElement.setAttribute(L"unit", Str::ToWString(aVoedingsmiddel.Getunit()).c_str());
}


}
