//=================================================
// GENERATED FILE, DON'T CHANGE MANUALLY
// GENERATED BY XmlElementGenerator
// To modify, adapt and run the XercesCodeGenerator
//=================================================
#include "generated/XmlVoedingswaarde.h"

#include <assert.h>
#include <tchar.h>


namespace ww_1_2
{
XmlVoedingswaarde::XmlVoedingswaarde()
: mkcalper100("-1")
, mvetper100("-1")
, mkoolhydratenper100("-1")
, meiwitper100("-1")
, mvezelsper100("-1")

{
}

XmlVoedingswaarde::~XmlVoedingswaarde()
{
}

std::string XmlVoedingswaarde::Getkcalper100() const
{
    return mkcalper100;
}

std::string XmlVoedingswaarde::Getvetper100() const
{
    return mvetper100;
}

std::string XmlVoedingswaarde::Getkoolhydratenper100() const
{
    return mkoolhydratenper100;
}

std::string XmlVoedingswaarde::Geteiwitper100() const
{
    return meiwitper100;
}

std::string XmlVoedingswaarde::Getvezelsper100() const
{
    return mvezelsper100;
}

void XmlVoedingswaarde::Setkcalper100(const std::string & akcalper100)
{
    mkcalper100 = akcalper100;
}

void XmlVoedingswaarde::Setvetper100(const std::string & avetper100)
{
    mvetper100 = avetper100;
}

void XmlVoedingswaarde::Setkoolhydratenper100(const std::string & akoolhydratenper100)
{
    mkoolhydratenper100 = akoolhydratenper100;
}

void XmlVoedingswaarde::Seteiwitper100(const std::string & aeiwitper100)
{
    meiwitper100 = aeiwitper100;
}

void XmlVoedingswaarde::Setvezelsper100(const std::string & avezelsper100)
{
    mvezelsper100 = avezelsper100;
}

}