//=================================================
// GENERATED FILE, DON'T CHANGE MANUALLY
// GENERATED BY XmlElementWriterGenerator
// To modify, adapt and run the XercesCodeGenerator
//=================================================

//=================================
// Generated by XmlWriterGenerator 
//=================================

#include "generated/XmlVoedingsmiddelheaderWriter.h"

#include <xercesc/dom/dom.hpp>
#include <xercesc/framework/LocalFileFormatTarget.hpp>
#include <xercesc/parsers/XercesDOMParser.hpp>

#include <Utilities/strutils.h>

#include "generated/XmlVoedingsmiddelheader.h"

namespace ww_1_2
{
XERCES_CPP_NAMESPACE::DOMNode * XmlVoedingsmiddelheaderWriter::Write(XERCES_CPP_NAMESPACE::DOMDocument & aDocument, const XmlVoedingsmiddelheader & aVoedingsmiddelheader)
{
    XERCES_CPP_NAMESPACE::DOMElement * element = aDocument.createElement(L"voedingsmiddelheader");
    Fill(aDocument, aVoedingsmiddelheader, *element);
    return element;
}

void XmlVoedingsmiddelheaderWriter::Fill(XERCES_CPP_NAMESPACE::DOMDocument & aDocument, const XmlVoedingsmiddelheader & aVoedingsmiddelheader, XERCES_CPP_NAMESPACE::DOMElement & anElement)
{
    (void)aDocument;
    (void)aVoedingsmiddelheader;
    (void)anElement;
  anElement.setAttribute(L"naam", Str::ToWString(aVoedingsmiddelheader.Getnaam()).c_str());
  anElement.setAttribute(L"categorie", Str::ToWString(aVoedingsmiddelheader.Getcategorie()).c_str());
  if (!aVoedingsmiddelheader.Getmerk().empty())
    anElement.setAttribute(L"merk", Str::ToWString(aVoedingsmiddelheader.Getmerk()).c_str());
  anElement.setAttribute(L"unit", Str::ToWString(aVoedingsmiddelheader.Getunit()).c_str());
}


}
