//=================================================
// GENERATED FILE, DON'T CHANGE MANUALLY
// GENERATED BY XmlElementWriterGenerator
// To modify, adapt and run the XercesCodeGenerator
//=================================================

//=================================
// Generated by XmlWriterGenerator 
//=================================

#include "generated/XmlVoedingsmiddeldefWriter.h"

#include <xercesc/dom/dom.hpp>
#include <xercesc/framework/LocalFileFormatTarget.hpp>
#include <xercesc/parsers/XercesDOMParser.hpp>

#include <Utilities/strutils.h>

#include "generated/XmlVoedingsmiddeldef.h"

#include "generated/XmlPortieWriter.h"
#include "generated/XmlPortie.h"
#include "generated/XmlVoedingsmiddelbasisWriter.h"
#include "generated/XmlVoedingsmiddelbasis.h"
#include "generated/XmlVoedingswaardeWriter.h"
#include "generated/XmlVoedingswaarde.h"
#include "generated/XmlPuntenper100Writer.h"
#include "generated/XmlPuntenper100.h"
namespace ww_1_2
{
XERCES_CPP_NAMESPACE::DOMNode * XmlVoedingsmiddeldefWriter::Write(XERCES_CPP_NAMESPACE::DOMDocument & aDocument, const XmlVoedingsmiddeldef & aVoedingsmiddeldef)
{
    XERCES_CPP_NAMESPACE::DOMElement * element = aDocument.createElement(L"voedingsmiddeldef");
    Fill(aDocument, aVoedingsmiddeldef, *element);
    return element;
}

void XmlVoedingsmiddeldefWriter::Fill(XERCES_CPP_NAMESPACE::DOMDocument & aDocument, const XmlVoedingsmiddeldef & aVoedingsmiddeldef, XERCES_CPP_NAMESPACE::DOMElement & anElement)
{

    XmlPortieWriter Portiewriter;
    for (size_t i = 0; i < aVoedingsmiddeldef.GetPortieList().size(); ++i)
    {
        XERCES_CPP_NAMESPACE::DOMNode * Portienode = Portiewriter.Write(aDocument, *aVoedingsmiddeldef.GetPortieList()[i]);
        anElement.appendChild(Portienode);
    }

    XmlVoedingsmiddelbasisWriter Voedingsmiddelbasiswriter;
    anElement.appendChild(Voedingsmiddelbasiswriter.Write(aDocument, aVoedingsmiddeldef.GetVoedingsmiddelbasis()));

    XmlVoedingswaardeWriter Voedingswaardewriter;
    if (aVoedingsmiddeldef.GetVoedingswaarde() != NULL)
        anElement.appendChild(Voedingswaardewriter.Write(aDocument, *aVoedingsmiddeldef.GetVoedingswaarde()));

    XmlPuntenper100Writer Puntenper100writer;
    if (aVoedingsmiddeldef.GetPuntenper100() != NULL)
        anElement.appendChild(Puntenper100writer.Write(aDocument, *aVoedingsmiddeldef.GetPuntenper100()));
    switch (aVoedingsmiddeldef.Getfavoriet())
    {
        case XmlVoedingsmiddeldef::favoriet::yes:
            anElement.setAttribute(L"favoriet", L"yes");
        break;
        case XmlVoedingsmiddeldef::favoriet::no:
            anElement.setAttribute(L"favoriet", L"no");
        break;
        default:
            throw 1;
    }
}


}
