//=================================================
// GENERATED FILE, DON'T CHANGE MANUALLY
// GENERATED BY XmlElementReaderGenerator
// To modify, adapt and run the XercesCodeGenerator
//=================================================
#include "generated/XmlVoedingsmiddelReader.h"

#include <xercesc/dom/dom.hpp>
#include <xercesc/parsers/XercesDOMParser.hpp>

#include <Utilities/strutils.h>

#include "generated/XmlVoedingsmiddel.h"
#include "generated/XmlStandardlotReader.h"
#include "generated/XmlStandardlot.h"
#include "generated/XmlFreelotReader.h"
#include "generated/XmlFreelot.h"


namespace ww_1_2
{
XmlVoedingsmiddelReader::XmlVoedingsmiddelReader()
{
}


std::unique_ptr<XmlVoedingsmiddel> XmlVoedingsmiddelReader::Generate(const XERCES_CPP_NAMESPACE::DOMNode & anElement)
{
    auto voedingsmiddel = std::make_unique<XmlVoedingsmiddel>();
    Fill(anElement, *voedingsmiddel);
    return voedingsmiddel;
}

XmlClass::Result XmlVoedingsmiddelReader::Fill(const XERCES_CPP_NAMESPACE::DOMNode & anElement, XmlVoedingsmiddel & aVoedingsmiddel)
{
    const XERCES_CPP_NAMESPACE::DOMNodeList * list = anElement.getChildNodes();

    if (list == nullptr)
        return XmlClass::Result::Ok;

    for (XMLSize_t i = 0; i < list->getLength(); i++) {
        if (list->item(i) == nullptr)
            continue;

        short type = list->item(i)->getNodeType();
        XERCES_CPP_NAMESPACE::DOMNode * node = list->item(i);

        if (type == XERCES_CPP_NAMESPACE::DOMNode::ELEMENT_NODE) {
     if (wcscmp(node->getNodeName(), L"standardlot") == 0)
     {
         XmlStandardlotReader standardlotReader;
         auto standardlot = standardlotReader.Generate(*node);
         if (standardlot != nullptr)
             aVoedingsmiddel.Setstandardlot(std::move(standardlot)); 
     }
     else if (wcscmp(node->getNodeName(), L"freelot") == 0)
     {
         XmlFreelotReader freelotReader;
         auto freelot = freelotReader.Generate(*node);
         if (freelot != nullptr)
             aVoedingsmiddel.Setfreelot(std::move(freelot)); 
     }
   }
  }
    const XERCES_CPP_NAMESPACE::DOMNamedNodeMap * attributes = anElement.getAttributes();
    if (attributes != nullptr)
    {
    const XERCES_CPP_NAMESPACE::DOMNode* naamnode = attributes->getNamedItem(L"naam");
    if (naamnode != nullptr)
      aVoedingsmiddel.Setnaam(Str::ToString(naamnode->getNodeValue()));
    const XERCES_CPP_NAMESPACE::DOMNode* categorienode = attributes->getNamedItem(L"categorie");
    if (categorienode != nullptr)
      aVoedingsmiddel.Setcategorie(Str::ToString(categorienode->getNodeValue()));
    const XERCES_CPP_NAMESPACE::DOMNode* merknode = attributes->getNamedItem(L"merk");
    if (merknode != nullptr)
      aVoedingsmiddel.Setmerk(Str::ToString(merknode->getNodeValue()));
    const XERCES_CPP_NAMESPACE::DOMNode* unitnode = attributes->getNamedItem(L"unit");
    if (unitnode != nullptr)
      aVoedingsmiddel.Setunit(Str::ToString(unitnode->getNodeValue()));
    }

    return XmlClass::Result::Ok;
}


}
