//=================================================
// GENERATED FILE, DON'T CHANGE MANUALLY
// GENERATED BY XmlElementReaderGenerator
// To modify, adapt and run the XercesCodeGenerator
//=================================================
#include "generated/XmlVoedingsmiddeldefReader.h"

#include <xercesc/dom/dom.hpp>
#include <xercesc/parsers/XercesDOMParser.hpp>

#include <Utilities/strutils.h>

#include "generated/XmlVoedingsmiddeldef.h"
#include "generated/XmlPortieReader.h"
#include "generated/XmlPortie.h"
#include "generated/XmlVoedingsmiddelbasisReader.h"
#include "generated/XmlVoedingsmiddelbasis.h"
#include "generated/XmlVoedingswaardeReader.h"
#include "generated/XmlVoedingswaarde.h"
#include "generated/XmlPuntenper100Reader.h"
#include "generated/XmlPuntenper100.h"


namespace ww_1_2
{
XmlVoedingsmiddeldefReader::XmlVoedingsmiddeldefReader()
{
}


std::unique_ptr<XmlVoedingsmiddeldef> XmlVoedingsmiddeldefReader::Generate(const XERCES_CPP_NAMESPACE::DOMNode & anElement)
{
    auto voedingsmiddeldef = std::make_unique<XmlVoedingsmiddeldef>();
    Fill(anElement, *voedingsmiddeldef);
    return voedingsmiddeldef;
}

XmlClass::Result XmlVoedingsmiddeldefReader::Fill(const XERCES_CPP_NAMESPACE::DOMNode & anElement, XmlVoedingsmiddeldef & aVoedingsmiddeldef)
{
    const XERCES_CPP_NAMESPACE::DOMNodeList * list = anElement.getChildNodes();

    if (list == nullptr)
        return XmlClass::Result::Ok;

    for (XMLSize_t i = 0; i < list->getLength(); i++) {
        if (list->item(i) == nullptr)
            continue;

        short type = list->item(i)->getNodeType();
        XERCES_CPP_NAMESPACE::DOMNode * node = list->item(i);

        if (type == XERCES_CPP_NAMESPACE::DOMNode::ELEMENT_NODE) {
     if (wcscmp(node->getNodeName(), L"portie") == 0)
     {
         XmlPortieReader portieReader;
         auto portie = portieReader.Generate(*node);
         if (portie != nullptr)
             aVoedingsmiddeldef.Add(std::move(portie));
     }
     else if (wcscmp(node->getNodeName(), L"voedingsmiddelbasis") == 0)
     {
         XmlVoedingsmiddelbasisReader voedingsmiddelbasisReader;
         auto voedingsmiddelbasis = voedingsmiddelbasisReader.Generate(*node);
         if (voedingsmiddelbasis != nullptr)
             aVoedingsmiddeldef.Setvoedingsmiddelbasis(std::move(voedingsmiddelbasis)); 
     }
     else if (wcscmp(node->getNodeName(), L"voedingswaarde") == 0)
     {
         XmlVoedingswaardeReader voedingswaardeReader;
         auto voedingswaarde = voedingswaardeReader.Generate(*node);
         if (voedingswaarde != nullptr)
             aVoedingsmiddeldef.Setvoedingswaarde(std::move(voedingswaarde)); 
     }
     else if (wcscmp(node->getNodeName(), L"puntenper100") == 0)
     {
         XmlPuntenper100Reader puntenper100Reader;
         auto puntenper100 = puntenper100Reader.Generate(*node);
         if (puntenper100 != nullptr)
             aVoedingsmiddeldef.Setpuntenper100(std::move(puntenper100)); 
     }
   }
  }
    const XERCES_CPP_NAMESPACE::DOMNamedNodeMap * attributes = anElement.getAttributes();
    if (attributes != nullptr)
    {
    const XERCES_CPP_NAMESPACE::DOMNode* favorietnode = attributes->getNamedItem(L"favoriet");
    if (favorietnode != nullptr)
    {
      if (wcscmp(favorietnode->getNodeValue(), L"yes") == 0)
        aVoedingsmiddeldef.Setfavoriet(XmlVoedingsmiddeldef::favoriet::yes);
      else if (wcscmp(favorietnode->getNodeValue(), L"no") == 0)
        aVoedingsmiddeldef.Setfavoriet(XmlVoedingsmiddeldef::favoriet::no);
    }
    }

    return XmlClass::Result::Ok;
}


}
