//=================================================
// GENERATED FILE, DON'T CHANGE MANUALLY
// GENERATED BY XmlElementGenerator
// To modify, adapt and run the XercesCodeGenerator
//=================================================
#include "generated/XmlVoedingsmiddelbasis.h"

#include <assert.h>
#include <tchar.h>

#include "generated/XmlVoedingsmiddelheader.h"

namespace ww_1_2
{
XmlVoedingsmiddelbasis::XmlVoedingsmiddelbasis()
    : mVoedingsmiddelheader(nullptr)    , mvrijeportie(vrijeportie::no)
    , mvrijeppportie(vrijeppportie::no)

{
}

XmlVoedingsmiddelbasis::~XmlVoedingsmiddelbasis()
{
}

XmlVoedingsmiddelheader & XmlVoedingsmiddelbasis::GetVoedingsmiddelheader()
{
    return *mVoedingsmiddelheader;
}

const XmlVoedingsmiddelheader & XmlVoedingsmiddelbasis::GetVoedingsmiddelheader() const
{
    return *mVoedingsmiddelheader;
}


void XmlVoedingsmiddelbasis::Setvoedingsmiddelheader(std::unique_ptr<XmlVoedingsmiddelheader> aVoedingsmiddelheader)
{
    assert(mVoedingsmiddelheader == nullptr);
    mVoedingsmiddelheader = std::move(aVoedingsmiddelheader);
}
std::string XmlVoedingsmiddelbasis::Getsterreportie() const
{
    return msterreportie;
}

XmlVoedingsmiddelbasis::vrijeportie XmlVoedingsmiddelbasis::Getvrijeportie() const
{
    return mvrijeportie;
}

std::string XmlVoedingsmiddelbasis::Getvrijepunten() const
{
    return mvrijepunten;
}

XmlVoedingsmiddelbasis::vrijeppportie XmlVoedingsmiddelbasis::Getvrijeppportie() const
{
    return mvrijeppportie;
}

std::string XmlVoedingsmiddelbasis::Getvrijepppunten() const
{
    return mvrijepppunten;
}

void XmlVoedingsmiddelbasis::Setsterreportie(const std::string & asterreportie)
{
    msterreportie = asterreportie;
}

void XmlVoedingsmiddelbasis::Setvrijeportie(vrijeportie avrijeportie)
{
    mvrijeportie = avrijeportie;
}

void XmlVoedingsmiddelbasis::Setvrijepunten(const std::string & avrijepunten)
{
    mvrijepunten = avrijepunten;
}

void XmlVoedingsmiddelbasis::Setvrijeppportie(vrijeppportie avrijeppportie)
{
    mvrijeppportie = avrijeppportie;
}

void XmlVoedingsmiddelbasis::Setvrijepppunten(const std::string & avrijepppunten)
{
    mvrijepppunten = avrijepppunten;
}

}