//=================================================
// GENERATED FILE, DON'T CHANGE MANUALLY
// GENERATED BY XmlElementWriterGenerator
// To modify, adapt and run the XercesCodeGenerator
//=================================================

//=================================
// Generated by XmlWriterGenerator 
//=================================

#include "generated/XmlVoedingsmiddelbasisWriter.h"

#include <xercesc/dom/dom.hpp>
#include <xercesc/framework/LocalFileFormatTarget.hpp>
#include <xercesc/parsers/XercesDOMParser.hpp>

#include <Utilities/strutils.h>

#include "generated/XmlVoedingsmiddelbasis.h"

#include "generated/XmlVoedingsmiddelheaderWriter.h"
#include "generated/XmlVoedingsmiddelheader.h"
namespace ww_1_2
{
XERCES_CPP_NAMESPACE::DOMNode * XmlVoedingsmiddelbasisWriter::Write(XERCES_CPP_NAMESPACE::DOMDocument & aDocument, const XmlVoedingsmiddelbasis & aVoedingsmiddelbasis)
{
    XERCES_CPP_NAMESPACE::DOMElement * element = aDocument.createElement(L"voedingsmiddelbasis");
    Fill(aDocument, aVoedingsmiddelbasis, *element);
    return element;
}

void XmlVoedingsmiddelbasisWriter::Fill(XERCES_CPP_NAMESPACE::DOMDocument & aDocument, const XmlVoedingsmiddelbasis & aVoedingsmiddelbasis, XERCES_CPP_NAMESPACE::DOMElement & anElement)
{

    XmlVoedingsmiddelheaderWriter Voedingsmiddelheaderwriter;
    anElement.appendChild(Voedingsmiddelheaderwriter.Write(aDocument, aVoedingsmiddelbasis.GetVoedingsmiddelheader()));
  anElement.setAttribute(L"sterreportie", Str::ToWString(aVoedingsmiddelbasis.Getsterreportie()).c_str());
    switch (aVoedingsmiddelbasis.Getvrijeportie())
    {
        case XmlVoedingsmiddelbasis::vrijeportie::yes:
            anElement.setAttribute(L"vrijeportie", L"yes");
        break;
        case XmlVoedingsmiddelbasis::vrijeportie::no:
            anElement.setAttribute(L"vrijeportie", L"no");
        break;
        default:
            throw 1;
    }
  anElement.setAttribute(L"vrijepunten", Str::ToWString(aVoedingsmiddelbasis.Getvrijepunten()).c_str());
    switch (aVoedingsmiddelbasis.Getvrijeppportie())
    {
        case XmlVoedingsmiddelbasis::vrijeppportie::yes:
            anElement.setAttribute(L"vrijeppportie", L"yes");
        break;
        case XmlVoedingsmiddelbasis::vrijeppportie::no:
            anElement.setAttribute(L"vrijeppportie", L"no");
        break;
        default:
            throw 1;
    }
  anElement.setAttribute(L"vrijepppunten", Str::ToWString(aVoedingsmiddelbasis.Getvrijepppunten()).c_str());
}


}
