//=================================================
// GENERATED FILE, DON'T CHANGE MANUALLY
// GENERATED BY XmlElementWriterGenerator
// To modify, adapt and run the XercesCodeGenerator
//=================================================

//=================================
// Generated by XmlWriterGenerator 
//=================================

#include "generated/XmlVoedingswaardeWriter.h"

#include <xercesc/dom/dom.hpp>
#include <xercesc/framework/LocalFileFormatTarget.hpp>
#include <xercesc/parsers/XercesDOMParser.hpp>

#include <Utilities/strutils.h>

#include "generated/XmlVoedingswaarde.h"

namespace ww_1_2
{
XERCES_CPP_NAMESPACE::DOMNode * XmlVoedingswaardeWriter::Write(XERCES_CPP_NAMESPACE::DOMDocument & aDocument, const XmlVoedingswaarde & aVoedingswaarde)
{
    XERCES_CPP_NAMESPACE::DOMElement * element = aDocument.createElement(L"voedingswaarde");
    Fill(aDocument, aVoedingswaarde, *element);
    return element;
}

void XmlVoedingswaardeWriter::Fill(XERCES_CPP_NAMESPACE::DOMDocument & aDocument, const XmlVoedingswaarde & aVoedingswaarde, XERCES_CPP_NAMESPACE::DOMElement & anElement)
{
    (void)aDocument;
    (void)aVoedingswaarde;
    (void)anElement;
  anElement.setAttribute(L"kcalper100", Str::ToWString(aVoedingswaarde.Getkcalper100()).c_str());
  anElement.setAttribute(L"vetper100", Str::ToWString(aVoedingswaarde.Getvetper100()).c_str());
  anElement.setAttribute(L"koolhydratenper100", Str::ToWString(aVoedingswaarde.Getkoolhydratenper100()).c_str());
  anElement.setAttribute(L"eiwitper100", Str::ToWString(aVoedingswaarde.Geteiwitper100()).c_str());
  anElement.setAttribute(L"vezelsper100", Str::ToWString(aVoedingswaarde.Getvezelsper100()).c_str());
}


}
