//=================================================
// GENERATED FILE, DON'T CHANGE MANUALLY
// GENERATED BY XmlElementGenerator
// To modify, adapt and run the XercesCodeGenerator
//=================================================
#include "generated/XmlVoedingsmiddelheader.h"

#include <assert.h>
#include <tchar.h>


namespace ww_1_2
{
XmlVoedingsmiddelheader::XmlVoedingsmiddelheader()
{
}

XmlVoedingsmiddelheader::~XmlVoedingsmiddelheader()
{
}

std::string XmlVoedingsmiddelheader::Getnaam() const
{
    return mnaam;
}

std::string XmlVoedingsmiddelheader::Getcategorie() const
{
    return mcategorie;
}

std::string XmlVoedingsmiddelheader::Getmerk() const
{
    return mmerk;
}

std::string XmlVoedingsmiddelheader::Getunit() const
{
    return munit;
}

void XmlVoedingsmiddelheader::Setnaam(const std::string & anaam)
{
    mnaam = anaam;
}

void XmlVoedingsmiddelheader::Setcategorie(const std::string & acategorie)
{
    mcategorie = acategorie;
}

void XmlVoedingsmiddelheader::Setmerk(const std::string & amerk)
{
    mmerk = amerk;
}

void XmlVoedingsmiddelheader::Setunit(const std::string & aunit)
{
    munit = aunit;
}

}