//=================================================
// GENERATED FILE, DON'T CHANGE MANUALLY
// GENERATED BY XmlElementGenerator
// To modify, adapt and run the XercesCodeGenerator
//=================================================
#include "generated/XmlVoedingsmiddeldef.h"

#include <assert.h>
#include <tchar.h>

#include "generated/XmlPortie.h"
#include "generated/XmlVoedingsmiddelbasis.h"
#include "generated/XmlVoedingswaarde.h"
#include "generated/XmlPuntenper100.h"

namespace ww_1_2
{
XmlVoedingsmiddeldef::XmlVoedingsmiddeldef()
    : mVoedingsmiddelbasis(nullptr)
    , mVoedingswaarde(nullptr)
    , mPuntenper100(nullptr)    , mfavoriet(favoriet::no)

{
}

XmlVoedingsmiddeldef::~XmlVoedingsmiddeldef()
{
}



const std::vector<std::unique_ptr<XmlPortie>> & XmlVoedingsmiddeldef::GetPortieList() const
{
    return mPortieList;
}
XmlVoedingsmiddelbasis & XmlVoedingsmiddeldef::GetVoedingsmiddelbasis()
{
    return *mVoedingsmiddelbasis;
}

const XmlVoedingsmiddelbasis & XmlVoedingsmiddeldef::GetVoedingsmiddelbasis() const
{
    return *mVoedingsmiddelbasis;
}
const XmlVoedingswaarde * XmlVoedingsmiddeldef::GetVoedingswaarde() const
{
    return mVoedingswaarde.get();
}
const XmlPuntenper100 * XmlVoedingsmiddeldef::GetPuntenper100() const
{
    return mPuntenper100.get();
}


void XmlVoedingsmiddeldef::Add(std::unique_ptr<XmlPortie> aPortie)
{
    mPortieList.push_back(std::move(aPortie));
}


void XmlVoedingsmiddeldef::Setvoedingsmiddelbasis(std::unique_ptr<XmlVoedingsmiddelbasis> aVoedingsmiddelbasis)
{
    assert(mVoedingsmiddelbasis == nullptr);
    mVoedingsmiddelbasis = std::move(aVoedingsmiddelbasis);
}


void XmlVoedingsmiddeldef::Setvoedingswaarde(std::unique_ptr<XmlVoedingswaarde> aVoedingswaarde)
{
    assert(mVoedingswaarde == nullptr);
    mVoedingswaarde = std::move(aVoedingswaarde);
}


void XmlVoedingsmiddeldef::Setpuntenper100(std::unique_ptr<XmlPuntenper100> aPuntenper100)
{
    assert(mPuntenper100 == nullptr);
    mPuntenper100 = std::move(aPuntenper100);
}
XmlVoedingsmiddeldef::favoriet XmlVoedingsmiddeldef::Getfavoriet() const
{
    return mfavoriet;
}

void XmlVoedingsmiddeldef::Setfavoriet(favoriet afavoriet)
{
    mfavoriet = afavoriet;
}

}