//=================================================
// GENERATED FILE, DON'T CHANGE MANUALLY
// GENERATED BY XmlModelGenerator
// To modify, adapt and run the XercesCodeGenerator
//=================================================
#include "generated/XmlVoedingsmiddeldefs.h"

#include <assert.h>
#include <tchar.h>

#include "generated/XmlVoedingsmiddeldef.h"

namespace ww_1_2
{
XmlVoedingsmiddeldefs::XmlVoedingsmiddeldefs()
{
}

XmlVoedingsmiddeldefs::~XmlVoedingsmiddeldefs()
{
}



const std::vector<std::unique_ptr<XmlVoedingsmiddeldef>> & XmlVoedingsmiddeldefs::GetVoedingsmiddeldefList() const
{
    return mVoedingsmiddeldefList;
}


void XmlVoedingsmiddeldefs::Add(std::unique_ptr<XmlVoedingsmiddeldef> aVoedingsmiddeldef)
{
    mVoedingsmiddeldefList.push_back(std::move(aVoedingsmiddeldef));
}
}