//=================================================
// GENERATED FILE, DON'T CHANGE MANUALLY
// GENERATED BY XmlElementReaderGenerator
// To modify, adapt and run the XercesCodeGenerator
//=================================================
#include "generated/XmlVoedingsmiddelheaderReader.h"

#include <xercesc/dom/dom.hpp>
#include <xercesc/parsers/XercesDOMParser.hpp>

#include <Utilities/strutils.h>

#include "generated/XmlVoedingsmiddelheader.h"


namespace ww_1_2
{
XmlVoedingsmiddelheaderReader::XmlVoedingsmiddelheaderReader()
{
}


std::unique_ptr<XmlVoedingsmiddelheader> XmlVoedingsmiddelheaderReader::Generate(const XERCES_CPP_NAMESPACE::DOMNode & anElement)
{
    auto voedingsmiddelheader = std::make_unique<XmlVoedingsmiddelheader>();
    Fill(anElement, *voedingsmiddelheader);
    return voedingsmiddelheader;
}

XmlClass::Result XmlVoedingsmiddelheaderReader::Fill(const XERCES_CPP_NAMESPACE::DOMNode & anElement, XmlVoedingsmiddelheader & aVoedingsmiddelheader)
{
    const XERCES_CPP_NAMESPACE::DOMNodeList * list = anElement.getChildNodes();

    if (list == nullptr)
        return XmlClass::Result::Ok;

    for (XMLSize_t i = 0; i < list->getLength(); i++) {
        if (list->item(i) == nullptr)
            continue;

  }
    const XERCES_CPP_NAMESPACE::DOMNamedNodeMap * attributes = anElement.getAttributes();
    if (attributes != nullptr)
    {
    const XERCES_CPP_NAMESPACE::DOMNode* naamnode = attributes->getNamedItem(L"naam");
    if (naamnode != nullptr)
      aVoedingsmiddelheader.Setnaam(Str::ToString(naamnode->getNodeValue()));
    const XERCES_CPP_NAMESPACE::DOMNode* categorienode = attributes->getNamedItem(L"categorie");
    if (categorienode != nullptr)
      aVoedingsmiddelheader.Setcategorie(Str::ToString(categorienode->getNodeValue()));
    const XERCES_CPP_NAMESPACE::DOMNode* merknode = attributes->getNamedItem(L"merk");
    if (merknode != nullptr)
      aVoedingsmiddelheader.Setmerk(Str::ToString(merknode->getNodeValue()));
    const XERCES_CPP_NAMESPACE::DOMNode* unitnode = attributes->getNamedItem(L"unit");
    if (unitnode != nullptr)
      aVoedingsmiddelheader.Setunit(Str::ToString(unitnode->getNodeValue()));
    }

    return XmlClass::Result::Ok;
}


}
