//=================================================
// GENERATED FILE, DON'T CHANGE MANUALLY
// GENERATED BY XmlElementGenerator
// To modify, adapt and run the XercesCodeGenerator
//=================================================
#include "generated/XmlVoedingsmiddel.h"

#include <assert.h>
#include <tchar.h>

#include "generated/XmlStandardlot.h"
#include "generated/XmlFreelot.h"

namespace ww_1_2
{
XmlVoedingsmiddel::XmlVoedingsmiddel()
    : mStandardlot(nullptr)
    , mFreelot(nullptr)
{
}

XmlVoedingsmiddel::~XmlVoedingsmiddel()
{
}

const XmlStandardlot * XmlVoedingsmiddel::GetStandardlot() const
{
    return mStandardlot.get();
}
const XmlFreelot * XmlVoedingsmiddel::GetFreelot() const
{
    return mFreelot.get();
}


void XmlVoedingsmiddel::Setstandardlot(std::unique_ptr<XmlStandardlot> aStandardlot)
{
    assert(mStandardlot == nullptr);
    mStandardlot = std::move(aStandardlot);
}


void XmlVoedingsmiddel::Setfreelot(std::unique_ptr<XmlFreelot> aFreelot)
{
    assert(mFreelot == nullptr);
    mFreelot = std::move(aFreelot);
}
std::string XmlVoedingsmiddel::Getnaam() const
{
    return mnaam;
}

std::string XmlVoedingsmiddel::Getcategorie() const
{
    return mcategorie;
}

std::string XmlVoedingsmiddel::Getmerk() const
{
    return mmerk;
}

std::string XmlVoedingsmiddel::Getunit() const
{
    return munit;
}

void XmlVoedingsmiddel::Setnaam(const std::string & anaam)
{
    mnaam = anaam;
}

void XmlVoedingsmiddel::Setcategorie(const std::string & acategorie)
{
    mcategorie = acategorie;
}

void XmlVoedingsmiddel::Setmerk(const std::string & amerk)
{
    mmerk = amerk;
}

void XmlVoedingsmiddel::Setunit(const std::string & aunit)
{
    munit = aunit;
}

}