//=================================================
// GENERATED FILE, DON'T CHANGE MANUALLY
// GENERATED BY XmlModelWriterGenerator
// To modify, adapt and run the XercesCodeGenerator
//=================================================

//=================================
// Generated by XmlWriterGenerator 
//=================================

#include "generated/XmlWeekWriter.h"

#include <xercesc/dom/dom.hpp>
#include <xercesc/framework/LocalFileFormatTarget.hpp>
#include <xercesc/parsers/XercesDOMParser.hpp>

#include <Utilities/strutils.h>

#include "generated/XmlWeek.h"

#include "generated/XmlDagWriter.h"
#include "generated/XmlDag.h"
namespace ww_1_2
{
XmlClass::Result XmlWeekWriter::Write(const std::string & aFilename, const XmlWeek & aWeek)
{
    ParseErrorHandler eh;
    XERCES_CPP_NAMESPACE::XercesDOMParser parser;
    parser.setDoValidation(false);
    parser.setErrorHandler(&eh);

    XERCES_CPP_NAMESPACE::DOMImplementation* impl =
      XERCES_CPP_NAMESPACE::DOMImplementationRegistry::getDOMImplementation(L"Core");

    XERCES_CPP_NAMESPACE::DOMDocument* doc =
      impl->createDocument(0,               // root element namespace URI.
                           L"week",  // root element name
                           0);              // document type object (Xml).
    XERCES_CPP_NAMESPACE::DOMElement* rootelement = doc->getDocumentElement();
    Fill(*doc, aWeek, *rootelement);

    XERCES_CPP_NAMESPACE::DOMWriter* writer = ((XERCES_CPP_NAMESPACE::DOMImplementationLS*)impl)->createDOMWriter();
    XERCES_CPP_NAMESPACE::LocalFileFormatTarget formatter(aFilename.c_str());
    writer->writeNode(&formatter, *doc);
    writer->release();

    doc->release();

    return Result::Ok;
}


void XmlWeekWriter::Fill(XERCES_CPP_NAMESPACE::DOMDocument & aDocument, const XmlWeek & aWeek, XERCES_CPP_NAMESPACE::DOMElement & anElement)
{

    XmlDagWriter Dagwriter;
    for (size_t i = 0; i < aWeek.GetDagList().size(); ++i)
    {
        XERCES_CPP_NAMESPACE::DOMNode * Dagnode = Dagwriter.Write(aDocument, *aWeek.GetDagList()[i]);
        anElement.appendChild(Dagnode);
    }
  anElement.setAttribute(L"begindatum", Str::ToWString(aWeek.Getbegindatum()).c_str());
  anElement.setAttribute(L"einddatum", Str::ToWString(aWeek.Geteinddatum()).c_str());
  anElement.setAttribute(L"punten", Str::ToWString(aWeek.Getpunten()).c_str());
  anElement.setAttribute(L"weekpunten", Str::ToWString(aWeek.Getweekpunten()).c_str());
  anElement.setAttribute(L"startweight", Str::ToWString(aWeek.Getstartweight()).c_str());
    switch (aWeek.Getstrategie())
    {
        case XmlWeek::strategie::FlexiPoints:
            anElement.setAttribute(L"strategie", L"FlexiPoints");
        break;
        case XmlWeek::strategie::ProPoints:
            anElement.setAttribute(L"strategie", L"ProPoints");
        break;
        case XmlWeek::strategie::KCal:
            anElement.setAttribute(L"strategie", L"KCal");
        break;
        case XmlWeek::strategie::CarboHydrates:
            anElement.setAttribute(L"strategie", L"CarboHydrates");
        break;
        default:
            throw 1;
    }
}


}
