//=================================================
// GENERATED FILE, DON'T CHANGE MANUALLY
// GENERATED BY XmlModelGenerator
// To modify, adapt and run the XercesCodeGenerator
//=================================================
#include "generated/XmlWeek.h"

#include <assert.h>
#include <tchar.h>

#include "generated/XmlDag.h"

namespace ww_1_2
{
XmlWeek::XmlWeek()
    : mstrategie(strategie::FlexiPoints)

{
}

XmlWeek::~XmlWeek()
{
}



const std::vector<std::unique_ptr<XmlDag>> & XmlWeek::GetDagList() const
{
    return mDagList;
}


void XmlWeek::Add(std::unique_ptr<XmlDag> aDag)
{
    mDagList.push_back(std::move(aDag));
}
std::string XmlWeek::Getbegindatum() const
{
    return mbegindatum;
}

std::string XmlWeek::Geteinddatum() const
{
    return meinddatum;
}

std::string XmlWeek::Getpunten() const
{
    return mpunten;
}

std::string XmlWeek::Getweekpunten() const
{
    return mweekpunten;
}

std::string XmlWeek::Getstartweight() const
{
    return mstartweight;
}

XmlWeek::strategie XmlWeek::Getstrategie() const
{
    return mstrategie;
}

void XmlWeek::Setbegindatum(const std::string & abegindatum)
{
    mbegindatum = abegindatum;
}

void XmlWeek::Seteinddatum(const std::string & aeinddatum)
{
    meinddatum = aeinddatum;
}

void XmlWeek::Setpunten(const std::string & apunten)
{
    mpunten = apunten;
}

void XmlWeek::Setweekpunten(const std::string & aweekpunten)
{
    mweekpunten = aweekpunten;
}

void XmlWeek::Setstartweight(const std::string & astartweight)
{
    mstartweight = astartweight;
}

void XmlWeek::Setstrategie(strategie astrategie)
{
    mstrategie = astrategie;
}

}