#ifndef WW_MODEL_XML01DEFINITIONS_H__
#define WW_MODEL_XML01DEFINITIONS_H__


#ifndef WW_GENERATED_NAMESPACE
#define WW_GENERATED_NAMESPACE Ww
#endif


#ifndef WW_NAMESPACE
#define WW_NAMESPACE WW_0_1
#endif


#endif// WW_MODEL_XML01DEFINITIONS_H__