//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by WeightControl.rc
//
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_WEIGHTWATCHERS_DIALOG       102
#define IDR_MAINFRAME                   128
#define IDD_PERSONALIA_PAGE             129
#define IDD_POINTSPERDAY                130
#define IDD_POINTSPERDAY_PAGE           130
#define IDD_DIALOG1                     131
#define IDD_DIARY_PAGE                  131
#define IDD_ITEMS_PAGE                  133
#define IDD_EDITFOOD_DIALOG             134
#define IDD_EDITPORTIE_DIALOG           135
#define IDD_FIND_VOEDINGSMIDDEL         137
#define IDD_RECEPTEN_PAGE               139
#define IDD_EDITRECEPT_DIALOG           140
#define IDD_EDIT_VOEDINGSMIDDEL         141
#define IDD_EDIT_RECEPT                 142
#define IDD_HANDMATIG_ITEM              148
#define IDD_DIALOG2                     149
#define IDD_FIND_RECEPT                 150
#define IDD_BONUSLIST                   152
#define IDD_EDIT_BONUS                  153
#define IDD_NEWNAME                     155
#define IDD_ADD_BEWEGING                159
#define IDC_TAB1                        1001
#define IDC_EDIT1                       1002
#define IDC_EDIT2                       1003
#define IDC_RADIO1                      1004
#define IDC_RADIO2                      1005
#define IDC_GEBOORTEDATUM               1007
#define IDC_STREEFGEWICHT               1012
#define IDC_PUNTEN                      1013
#define IDC_CALCULATE                   1014
#define IDC_ZITTEND                     1020
#define IDC_STAAND                      1021
#define IDC_RADIO7                      1022
#define IDC_ZWAAR                       1023
#define IDC_LENGTE                      1024
#define IDC_STARTGEWICHT                1025
#define IDC_EDIT3                       1026
#define IDC_PUNTENTOTAAL                1026
#define IDC_WEEK_EINDE                  1026
#define IDC_DATETIMEPICKER1             1027
#define IDC_HUIDIGGEWICHT               1027
#define IDC_LIST2                       1030
#define IDC_ITEMLIST                    1030
#define IDC_ITEMS_LIST                  1030
#define IDC_BUTTON2                     1033
#define IDC_DAY_PLUS                    1033
#define IDC_PORTIE                      1034
#define IDC_DELETE                      1035
#define IDC_ADD                         1036
#define IDC_EDIT                        1037
#define IDC_NAAM                        1038
#define IDC_OMSCHRIJVING                1038
#define IDC_COMBO1                      1039
#define IDC_EDIT4                       1040
#define IDC_VETPER100                   1040
#define IDC_EDIT5                       1041
#define IDC_POINTS                      1041
#define IDC_WEEKPUNTEN                  1041
#define IDC_AMOUNT                      1044
#define IDC_VMNAAM                      1046
#define IDC_UNITAMOUNT                  1047
#define IDC_UNIT                        1048
#define IDC_KCALPER100                  1049
#define IDC_CATEGORIE                   1050
#define IDC_VROUWELIJK                  1051
#define IDC_MANNELIJK                   1052
#define IDC_GEBOREN                     1053
#define IDC_LOPEND                      1055
#define IDC_RADIO5                      1056
#define IDC_ADD_FOOD                    1058
#define IDC_UNITS                       1064
#define IDC_PORTIES                     1065
#define IDC_PORTIENAAM                  1066
#define IDC_WEEK_BEGIN                  1067
#define IDC_SPIN_WEEK_EINDE             1069
#define IDC_BONUSPUNTEN                 1070
#define IDC_PUNTEN_OVER                 1071
#define IDC_DAY_MINUS                   1072
#define IDC_DATE                        1073
#define IDC_LIST1                       1074
#define IDC_AANTAL_PORTIES              1075
#define IDC_AANTAL_UNITS                1076
#define IDC_VOEDINGSMIDDELNAAM          1077
#define IDC_ADD_RECEPT                  1078
#define IDC_ADD_GERECHT                 1079
#define IDC_WEIGHT                      1083
#define IDC_PUNTEN_STATIC               1085
#define IDC_ADD_HANDMATIG               1091
#define IDC_TOTAAL                      1092
#define IDC_EIWITTEN_PER_100            1093
#define IDC_KOOLHYDRATEN_PER_100        1094
#define IDC_VEZELS_PER_100              1095
#define IDC_WEEKPUNTENSTATIC            1096
#define IDC_STRATEGIE                   1097
#define IDC_RADIO_KCAL                  1097
#define IDC_COMBO2                      1098
#define IDC_BRAND                       1099
#define IDS_KCAL_PER_100                1101
#define IDS_EIWIT_PER_100               1102
#define IDS_KOOLHYDRATEN_PER_100        1103
#define IDS_VET_PER_100                 1104
#define IDS_VEZELS_PER_100              1105
#define IDC_PER_STATIC                  1110
#define IDC_EENHEDEN_STATIC             1111
#define IDC_EENHEDEN                    1112
#define IDC_ADDBINUS                    1114
#define IDC_ADDBONUS                    1114
#define IDC_CALCULATEDBONUS             1115
#define IDC_INTENSITY_GROUP             1119
#define IDC_RADIO_HIGH                  1120
#define IDC_RADIO_LOW                   1121
#define IDC_RADIO_MEDIUM                1122
#define IDC_GEWICHT                     1123
#define IDC_DUUR                        1124
#define IDC_BONUSLISTJBJ                1125
#define IDC_CHECK_FAVOURITES            1126
#define IDC_CHECK_FAVOURITE             1127
#define IDC_CHECK1                      1128
#define IDC_CARBOHYDRATES               1129
#define IDC_RADIO_CARBOHYDRATES         1129
#define IDC_NAME                        1130
#define IDC_EDIT_CALORIES               1132

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        161
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1133
#define _APS_NEXT_SYMED_VALUE           104
#endif
#endif
